#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using IRIT.EdMS.WebUI;
    
    #line 3 "..\..\Areas\Security\Views\User\Edit.cshtml"
    using IRIT.EdMS.WebUI.RazorHelpers;
    
    #line default
    #line hidden
    using IRIT.Framework.Resources;
    
    #line 4 "..\..\Areas\Security\Views\User\Edit.cshtml"
    using IRIT.Framework.Utility.Helpers;
    
    #line default
    #line hidden
    using Kendo.Mvc.UI;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Security/Views/User/Edit.cshtml")]
    public partial class _Areas_Security_Views_User_Edit_cshtml : System.Web.Mvc.WebViewPage<IRIT.EdMS.Security.Model.ViewModel.User.UserViewModel>
    {
        public _Areas_Security_Views_User_Edit_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 6 "..\..\Areas\Security\Views\User\Edit.cshtml"
  
    ViewBag.Title =GeneralResource.EditUser;

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n");

            
            #line 11 "..\..\Areas\Security\Views\User\Edit.cshtml"
        
            
            #line default
            #line hidden
            
            #line 11 "..\..\Areas\Security\Views\User\Edit.cshtml"
         using (Html.BeginForm(MVC.Security.User.ActionNames.Edit, MVC.Security.User.Name, new { area = MVC.Security.Name }, FormMethod.Post, new { User = "form", @class = "form-horizontal", autocomplete = "off", id = "editUserForm" }))
        {
            
            
            #line default
            #line hidden
            
            #line 13 "..\..\Areas\Security\Views\User\Edit.cshtml"
       Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 13 "..\..\Areas\Security\Views\User\Edit.cshtml"
                                    
            
            
            #line default
            #line hidden
            
            #line 14 "..\..\Areas\Security\Views\User\Edit.cshtml"
       Write(Html.HiddenFor(a => a.Id));

            
            #line default
            #line hidden
            
            #line 14 "..\..\Areas\Security\Views\User\Edit.cshtml"
                                      

            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" class=\"panel panel-default\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"panel-heading\"");

WriteLiteral(">\r\n                    <strong>");

            
            #line 17 "..\..\Areas\Security\Views\User\Edit.cshtml"
                       Write(GeneralResource.Specifications);

            
            #line default
            #line hidden
WriteLiteral("</strong>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"panel-body\"");

WriteLiteral(">\r\n                    <ul");

WriteLiteral(" class=\"nav nav-tabs\"");

WriteLiteral(">\r\n                        <li");

WriteLiteral(" class=\"active\"");

WriteLiteral(">\r\n                            <a");

WriteLiteral(" href=\"#requiredInfo\"");

WriteLiteral(" data-toggle=\"tab\"");

WriteLiteral(">");

            
            #line 22 "..\..\Areas\Security\Views\User\Edit.cshtml"
                                                                 Write(GeneralResource.Specifications);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n                        </li>                       \r\n                     " +
"   <li>\r\n                            <a");

WriteLiteral(" href=\"#permissions\"");

WriteLiteral(" data-toggle=\"tab\"");

WriteLiteral(">");

            
            #line 25 "..\..\Areas\Security\Views\User\Edit.cshtml"
                                                                Write(GeneralResource.Access);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n                        </li>\r\n                        <li>\r\n              " +
"              <a");

WriteLiteral(" href=\"#settings\"");

WriteLiteral(" data-toggle=\"tab\"");

WriteLiteral(">");

            
            #line 28 "..\..\Areas\Security\Views\User\Edit.cshtml"
                                                             Write(GeneralResource.UserSettings);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n                        </li>\r\n                        <li>\r\n              " +
"              <a");

WriteLiteral(" href=\"#roles\"");

WriteLiteral(" data-toggle=\"tab\"");

WriteLiteral(">");

            
            #line 31 "..\..\Areas\Security\Views\User\Edit.cshtml"
                                                          Write(GeneralResource.UserGroups);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n                        </li>\r\n                    </ul>\r\n                 " +
"   <div");

WriteLiteral(" class=\"tab-content\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"tab-pane active\"");

WriteLiteral(" style=\"padding-top:20px;\"");

WriteLiteral(" id=\"requiredInfo\"");

WriteLiteral(">                           \r\n                            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 37 "..\..\Areas\Security\Views\User\Edit.cshtml"
                           Write(Html.LabelFor(m => m.UserName, new { @class = "col-md-2 control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 39 "..\..\Areas\Security\Views\User\Edit.cshtml"
                               Write(Html.NoAutoCompleteTextBoxForLtr(m => m.UserName));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                    ");

            
            #line 40 "..\..\Areas\Security\Views\User\Edit.cshtml"
                               Write(Html.ValidationMessageFor(m => m.UserName, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </div>\r\n                            </div>\r\n   " +
"                        \r\n                        </div>\r\n                      " +
" \r\n                        <div");

WriteLiteral(" class=\"tab-pane\"");

WriteLiteral(" id=\"permissions\"");

WriteLiteral(">\r\n                                ");

WriteLiteral("\r\n                            </div>\r\n                        <div");

WriteLiteral(" class=\"tab-pane\"");

WriteLiteral(" id=\"settings\"");

WriteLiteral(">\r\n                            ");

WriteLiteral("\r\n                        </div>\r\n                        <div");

WriteLiteral(" class=\"tab-pane\"");

WriteLiteral(" id=\"roles\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 71 "..\..\Areas\Security\Views\User\Edit.cshtml"
                       Write(CheckBoxListBuilder.CheckBoxList("UserGroupIds", ViewBag.UsersGroups));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                    </div>\r\n                </d" +
"iv>\r\n                <div");

WriteLiteral(" class=\"panel-footer\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n                            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 4481), Tuple.Create("\"", 4560)
            
            #line 78 "..\..\Areas\Security\Views\User\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 4488), Tuple.Create<System.Object, System.Int32>(Url.Action(MVC.Security.User.ActionNames.Index, MVC.Security.User.Name)
            
            #line default
            #line hidden
, 4488), false)
);

WriteLiteral(" class=\"btn btn-danger\"");

WriteLiteral(">\r\n                                <i");

WriteLiteral(" class=\"fa fa-lg fa-arrow-right\"");

WriteLiteral("></i> ");

            
            #line 79 "..\..\Areas\Security\Views\User\Edit.cshtml"
                                                                   Write(GeneralResource.Back);

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </a>\r\n                            <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" autocomplete=\"off\"");

WriteLiteral(" class=\"btn btn-success\"");

WriteLiteral(">\r\n                                <i");

WriteLiteral(" class=\"fa fa-lg fa-save\"");

WriteLiteral("></i>  ");

            
            #line 82 "..\..\Areas\Security\Views\User\Edit.cshtml"
                                                             Write(GeneralResource.Save);

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </button>                           \r\n             " +
"           </div>\r\n                    </div>\r\n                </div>\r\n         " +
"   </div>\r\n");

            
            #line 88 "..\..\Areas\Security\Views\User\Edit.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n</div>\r\n");

DefineSection("Scripts", () => {

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 92 "..\..\Areas\Security\Views\User\Edit.cshtml"
Write(Scripts.Render("~/bundles/jqueryval"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <script>\r\n        $(function () {\r\n            warningBeforeLoad();\r\n      " +
"      makeUploadFile(\"AvatarImage\");\r\n        });\r\n    </script>\r\n");

});

WriteLiteral("\r\n\r\n\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
