#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using IRIT.EdMS.WebUI;
    using IRIT.Framework.Resources;
    using Kendo.Mvc.UI;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Security/Views/User/Index.cshtml")]
    public partial class _Areas_Security_Views_User_Index_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Areas_Security_Views_User_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Areas\Security\Views\User\Index.cshtml"
  
    ViewBag.Title = GeneralResource.UserManagement;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 5 "..\..\Areas\Security\Views\User\Index.cshtml"
Write(Styles.Render("~/Content/bootstrap-dialog"));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-md-5\"");

WriteLiteral(" style=\"padding-bottom: 10px;\"");

WriteLiteral(">\r\n                <a");

WriteAttribute("href", Tuple.Create(" href=\"", 269), Tuple.Create("\"", 349)
            
            #line 11 "..\..\Areas\Security\Views\User\Index.cshtml"
, Tuple.Create(Tuple.Create("", 276), Tuple.Create<System.Object, System.Int32>(Url.Action(MVC.Security.User.ActionNames.Create, MVC.Security.User.Name)
            
            #line default
            #line hidden
, 276), false)
);

WriteLiteral(" class=\"btn btn-success\"");

WriteLiteral(">\r\n                    <i");

WriteLiteral(" class=\"fa fa-lg fa-plus\"");

WriteLiteral("></i> ");

            
            #line 12 "..\..\Areas\Security\Views\User\Index.cshtml"
                                                Write(GeneralResource.New);

            
            #line default
            #line hidden
WriteLiteral("\r\n                </a>\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"panel panel-primary\"");

WriteLiteral(">\r\n            \r\n            <div");

WriteLiteral(" class=\"panel-heading\"");

WriteLiteral(">\r\n                <i");

WriteLiteral(" class=\"fa fa-lg fa-user\"");

WriteLiteral("></i> ");

            
            #line 19 "..\..\Areas\Security\Views\User\Index.cshtml"
                                            Write(GeneralResource.UserList);

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"k-rtl\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 22 "..\..\Areas\Security\Views\User\Index.cshtml"
            Write(Html.Kendo().Grid<IRIT.EdMS.Security.Model.ViewModel.User.UserListViewModel>().Name("grid_user")
                      .Columns(columns =>
                      {
                          columns.Bound(c => c.FirstName).Width(190);
                          columns.Bound(c => c.LastName).Width(190);
                          columns.Bound(c => c.UserName);
                          columns.Template(x => { }).ClientTemplate(
                              "<a class='btn btn-warning' href='" + Url.Action(MVC.Security.User.ActionNames.Edit, MVC.Security.User.Name) + "?id=#= ID #'" + ">" + GeneralResource.Edit + "</a>" +
                              "<a class='btn-danger btn' target='#= ID #'>" + GeneralResource.Delete + "</a>");
                      })
                      .HtmlAttributes(new {style = "height: 480px;"})
                      .Scrollable()
                      .Sortable()
                      .Filterable(flt =>
                      {
                          flt.Mode(GridFilterMode.Menu);
                          flt.Operators(fltOpt =>
                          {
                              fltOpt.ForString(fms =>
                              {
                                  fms.IsEqualTo(GeneralResource.EqualsTo);
                                  fms.IsNotEqualTo(GeneralResource.IsNotEqualTo);
                                  fms.StartsWith(GeneralResource.StartsWith);
                                  fms.EndsWith(GeneralResource.EndsWith);
                                  fms.Contains(GeneralResource.Contains);
                                  fms.DoesNotContain(GeneralResource.DoesNotContain);
                              });
                              //fltOpt.ForDate(fms => { fms.IsEqualTo(GeneralResource.Equals); fms.IsNotEqualTo(GeneralResource.IsNotEqualTo); fms.StartsWith(GeneralResource.StartsWith); fms.EndsWith(GeneralResource.EndsWith); fms.Contains(GeneralResource.Contains); fms.DoesNotContain(GeneralResource.DoesNotContain); });
                          });
                      })
                      .Groupable(grp => { grp.Messages(gmsg => { gmsg.Empty(GeneralResource.DragColumnToGroup); }); })
                      .Pageable(pageable => pageable.Refresh(true).PageSizes(true).ButtonCount(5).Messages(msg =>
                      {
                          msg.Display(GeneralResource.GridPagingMessage);
                          msg.ItemsPerPage(GeneralResource.ItemsPerPage);
                          msg.Refresh(GeneralResource.Refresh);
                          msg.Last(GeneralResource.Last);
                          msg.Next(GeneralResource.Next);
                          msg.Previous(GeneralResource.Previous);
                          msg.First(GeneralResource.First);
                      }))
                      .DataSource(dataBinding => dataBinding.Ajax().Model(model => model.Id(id => id.Id))
                          .Read(read => read.Action(MVC.Security.User.ActionNames.Users_Read, MVC.Security.User.Name)))
                      );

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n        \r\n    </div>\r\n\r\n</div>\r\n\r\n");

DefineSection("Scripts", () => {

WriteLiteral(@"
    <script>
        $(document).on('click', '.btn-danger', function () {
            var rowToDelete = $(this).closest(""tr"");
            var grid = $(""#grid_user"").data(""kendoGrid"");

            var pkNo = $(this).attr(""target"");
            var rowNo = '#row-' + pkNo;
            BootstrapDialog.show({
                title: '',
                message: '");

            
            #line 84 "..\..\Areas\Security\Views\User\Index.cshtml"
                     Write(GeneralResource.SureDelete);

            
            #line default
            #line hidden
WriteLiteral("\',\r\n                buttons: [{\r\n                    label: \'بلی\',\r\n             " +
"       action: function (dialog) {\r\n                        $.ajax({\r\n          " +
"                  type: \"POST\",\r\n                            url: \"");

            
            #line 90 "..\..\Areas\Security\Views\User\Index.cshtml"
                             Write(Url.Action(MVC.Security.User.ActionNames.Delete, MVC.Security.User.Name));

            
            #line default
            #line hidden
WriteLiteral(@""",
                            data: { id: pkNo },
                            cache: false,
                            dataType: ""json"",
                            success: function () {
                                dialog.close();
                                grid.removeRow(rowToDelete);
                            },

                            error: function (jqXHR, exception) {
                                alert('Uncaught Error.\n' + jqXHR.responseText);
                            }
                        });
                    }
                }, {
                    label: 'خیر',
                    action: function (dialog) {
                        dialog.close();
                    }
                }]

            });

        });
    </script>
");

});

        }
    }
}
#pragma warning restore 1591
