#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Areas\Security\Views\Account\Login.cshtml"
    using CaptchaMvc.HtmlHelpers;
    
    #line default
    #line hidden
    using IRIT.EdMS.WebUI;
    using IRIT.Framework.Resources;
    
    #line 2 "..\..\Areas\Security\Views\Account\Login.cshtml"
    using IRIT.Framework.Utility.Helpers;
    
    #line default
    #line hidden
    using Kendo.Mvc.UI;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Security/Views/Account/Login.cshtml")]
    public partial class _Areas_Security_Views_Account_Login_cshtml : System.Web.Mvc.WebViewPage<IRIT.EdMS.Security.Model.ViewModel.Account.LoginViewModel>
    {
        public _Areas_Security_Views_Account_Login_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 5 "..\..\Areas\Security\Views\Account\Login.cshtml"
  
    ViewBag.Title = GeneralResource.SchoolManagementSystem;
    Layout = "~/Views/Shared/_LayoutUnauthorize.cshtml";

            
            #line default
            #line hidden
WriteLiteral(@"
<style>
    html {
        position: relative;
        min-height: 100%;
    }
    body {
        background: white;
        margin: 50px 0;
    }
    header, footer {
        background: lightseagreen;
        width: 100%;
        height: 50px;
    }
    header {
        position: fixed;
        left: 0;
        top: 0;
    }
    footer {
        position: absolute;
        left: 0;
        bottom: 0;
    }
    .container {
        width: 70%;
        margin: 0 auto;
        background: white;
        min-height: calc(100vh - 100px);
    }
</style>

<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"col-md-5 col-sm-offset-5\"");

WriteLiteral(">\r\n        <img");

WriteAttribute("src", Tuple.Create(" src=\"", 928), Tuple.Create("\"", 977)
, Tuple.Create(Tuple.Create("", 934), Tuple.Create<System.Object, System.Int32>(Href("~/Content/Image/Icon/in_the_name_of_GOD.gif")
, 934), false)
);

WriteLiteral(" width=\"80\"");

WriteLiteral(" height=\"80\"");

WriteLiteral(" style=\"margin-bottom: 30px; margin-right: 100px;\"");

WriteLiteral("/>\r\n    </div>\r\n</div>\r\n    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n");

            
            #line 47 "..\..\Areas\Security\Views\Account\Login.cshtml"
        
            
            #line default
            #line hidden
            
            #line 47 "..\..\Areas\Security\Views\Account\Login.cshtml"
         using (Html.BeginForm(MVC.Security.Account.ActionNames.Login, MVC.Security.Account.Name, new { ViewBag.ReturnUrl, area = MVC.Security.Account.Area }, FormMethod.Post, new { @class = "form-horizontal", role = "form", id = "loginForm", autocomplete = "off" }))
        {
            
            
            #line default
            #line hidden
            
            #line 49 "..\..\Areas\Security\Views\Account\Login.cshtml"
       Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 49 "..\..\Areas\Security\Views\Account\Login.cshtml"
                                    

            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" class=\"col-md-4 col-sm-offset-4\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"panel  panel-default\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"panel-heading\"");

WriteLiteral(">\r\n                        <strong> ورود به حساب کاربری</strong>\r\n               " +
"     </div>\r\n                    <div");

WriteLiteral(" class=\"panel-body\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(" style=\"margin-top: 20px;\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 57 "..\..\Areas\Security\Views\Account\Login.cshtml"
                       Write(Html.LabelFor(m => m.UserName, new { @class = "col-md-3 control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            <div");

WriteLiteral(" class=\"col-md-8\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 59 "..\..\Areas\Security\Views\Account\Login.cshtml"
                           Write(Html.NoAutoCompleteTextBoxForLtr(m => m.UserName));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                ");

            
            #line 60 "..\..\Areas\Security\Views\Account\Login.cshtml"
                           Write(Html.ValidationMessageFor(m => m.UserName, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </div>\r\n                        </div>\r\n           " +
"             <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 64 "..\..\Areas\Security\Views\Account\Login.cshtml"
                       Write(Html.LabelFor(m => m.Password, new { @class = "col-md-3 control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            <div");

WriteLiteral(" class=\"col-md-8\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 66 "..\..\Areas\Security\Views\Account\Login.cshtml"
                           Write(Html.FormControlPasswordFor(m => m.Password));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                ");

            
            #line 67 "..\..\Areas\Security\Views\Account\Login.cshtml"
                           Write(Html.ValidationMessageFor(m => m.Password, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </div>\r\n                        </div>\r\n           " +
"             <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"col-md-4 col-md-offset-3\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 72 "..\..\Areas\Security\Views\Account\Login.cshtml"
                           Write(Html.CheckBoxFor(m => m.RememberMe, new { @class = "checkbox-inline" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                ");

            
            #line 73 "..\..\Areas\Security\Views\Account\Login.cshtml"
                           Write(Html.LabelFor(m => m.RememberMe, new { @class = "control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </div>\r\n                        </div>\r\n");

            
            #line 76 "..\..\Areas\Security\Views\Account\Login.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 76 "..\..\Areas\Security\Views\Account\Login.cshtml"
                         if (ViewData.ModelState[""] != null && ViewData.ModelState[""].Errors.Count > 0)
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <div");

WriteLiteral(" class=\"alert alert-error\"");

WriteLiteral(" style=\"background-color: rgb(247, 147, 128);\"");

WriteLiteral(">\r\n                                <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"close\"");

WriteLiteral(" data-dismiss=\"alert\"");

WriteLiteral(">×</button>\r\n");

WriteLiteral("                                ");

            
            #line 80 "..\..\Areas\Security\Views\Account\Login.cshtml"
                           Write(Html.ValidationSummary(true, GeneralResource.Error+" "));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </div>\r\n");

            
            #line 82 "..\..\Areas\Security\Views\Account\Login.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                    </div>\r\n                    <div");

WriteLiteral(" class=\"panel-footer\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"col-md-2\"");

WriteLiteral(">\r\n                                <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" autocomplete=\"off\"");

WriteLiteral(" class=\"btn btn-success\"");

WriteLiteral(" id=\"btn-login\"");

WriteLiteral(">\r\n                                    <i");

WriteLiteral(" class=\"glyphicon glyphicon-log-in\"");

WriteLiteral("></i> ");

            
            #line 88 "..\..\Areas\Security\Views\Account\Login.cshtml"
                                                                          Write(GeneralResource.Login);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </button>\r\n                            </div>\r\n" +
"                        </div>\r\n                    </div>\r\n                </di" +
"v>\r\n            </div>\r\n");

            
            #line 95 "..\..\Areas\Security\Views\Account\Login.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n\r\n");

DefineSection("Scripts", () => {

            
            #line 98 "..\..\Areas\Security\Views\Account\Login.cshtml"
    
            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 99 "..\..\Areas\Security\Views\Account\Login.cshtml"
   Write(Scripts.Render("~/bundles/jqueryval"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");

});

        }
    }
}
#pragma warning restore 1591
