#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRIT.EdMS.WebUI.RazorHelpers
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    
    #line 2 "..\..\RazorHelpers\ImageUploadBuilder.cshtml"
    using System.Web.Mvc;
    
    #line default
    #line hidden
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public class ImageUploadBuilder : System.Web.WebPages.HelperPage
    {

#line 4 "..\..\RazorHelpers\ImageUploadBuilder.cshtml"
public static System.Web.WebPages.HelperResult ImageUpload(string name, string imageSrc)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 5 "..\..\RazorHelpers\ImageUploadBuilder.cshtml"
 


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "    <div");

WriteLiteralTo(__razor_helper_writer, " class=\"container\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n        <div");

WriteLiteralTo(__razor_helper_writer, " class=\"row\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n            <div");

WriteLiteralTo(__razor_helper_writer, " class=\"col-xs-12 col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n                <!-- image-preview-filename input [CUT FROM HERE]-->\r\n        " +
"        <div");

WriteLiteralTo(__razor_helper_writer, " class=\"input-group image-preview\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n                    <input");

WriteLiteralTo(__razor_helper_writer, " type=\"text\"");

WriteLiteralTo(__razor_helper_writer, " class=\"form-control image-preview-filename\"");

WriteLiteralTo(__razor_helper_writer, " disabled=\"disabled\"");

WriteLiteralTo(__razor_helper_writer, "> <!-- don\'t give a name === doesn\'t send on POST/GET -->\r\n                    <s" +
"pan");

WriteLiteralTo(__razor_helper_writer, " class=\"input-group-btn\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n                        <!-- image-preview-clear button -->\r\n                 " +
"       <button");

WriteLiteralTo(__razor_helper_writer, " type=\"button\"");

WriteLiteralTo(__razor_helper_writer, " class=\"btn btn-default image-preview-clear\"");

WriteLiteralTo(__razor_helper_writer, " style=\"display:none;\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n                            <span");

WriteLiteralTo(__razor_helper_writer, " class=\"glyphicon glyphicon-remove\"");

WriteLiteralTo(__razor_helper_writer, "></span> Clear\r\n                        </button>\r\n                        <!-- i" +
"mage-preview-input -->\r\n                        <div");

WriteLiteralTo(__razor_helper_writer, " class=\"btn btn-default image-preview-input\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n                            <span");

WriteLiteralTo(__razor_helper_writer, " class=\"glyphicon glyphicon-folder-open\"");

WriteLiteralTo(__razor_helper_writer, "></span>\r\n                            <span");

WriteLiteralTo(__razor_helper_writer, " class=\"image-preview-input-title\"");

WriteLiteralTo(__razor_helper_writer, ">Browse</span>\r\n                            <input");

WriteLiteralTo(__razor_helper_writer, " type=\"file\"");

WriteLiteralTo(__razor_helper_writer, " accept=\"image/png, image/jpeg, image/gif\"");

WriteLiteralTo(__razor_helper_writer, " name=\"input-file-preview\"");

WriteLiteralTo(__razor_helper_writer, " /> <!-- rename it -->\r\n                        </div>\r\n                    </spa" +
"n>\r\n                </div><!-- /input-group image-preview [TO HERE]-->\r\n        " +
"    </div>\r\n        </div>\r\n    </div>\r\n");


#line 28 "..\..\RazorHelpers\ImageUploadBuilder.cshtml"


#line default
#line hidden
});

#line 28 "..\..\RazorHelpers\ImageUploadBuilder.cshtml"
}
#line default
#line hidden

    }
}
#pragma warning restore 1591
