#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRIT.EdMS.WebUI.RazorHelpers
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 6 "..\..\RazorHelpers\NotyBuilder.cshtml"
    using IRIT.Framework.Utility.Controller.NotyHelper;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public class NotyBuilder : System.Web.WebPages.HelperPage
    {

#line 8 "..\..\RazorHelpers\NotyBuilder.cshtml"
public static System.Web.WebPages.HelperResult ShowNotyMessages(Noty notyInput)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 9 "..\..\RazorHelpers\NotyBuilder.cshtml"
 
    if (notyInput == null)
    {
        return;
    }



#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "    <script>\n    $(function() {\n\n");


#line 18 "..\..\RazorHelpers\NotyBuilder.cshtml"
        

#line default
#line hidden

#line 18 "..\..\RazorHelpers\NotyBuilder.cshtml"
         foreach (var message in notyInput.NotyMessages)
            {


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "                ");

WriteLiteralTo(__razor_helper_writer, "var  overrideOptions= {};\n");

WriteLiteralTo(__razor_helper_writer, "                ");

WriteLiteralTo(__razor_helper_writer, " overrideOptions.layout= \'");


#line 21 "..\..\RazorHelpers\NotyBuilder.cshtml"
              WriteTo(__razor_helper_writer, message.Location);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\';\n");

WriteLiteralTo(__razor_helper_writer, "                ");

WriteLiteralTo(__razor_helper_writer, "overrideOptions.type= \'");


#line 22 "..\..\RazorHelpers\NotyBuilder.cshtml"
           WriteTo(__razor_helper_writer, message.Type);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\';\n");

WriteLiteralTo(__razor_helper_writer, "                ");

WriteLiteralTo(__razor_helper_writer, "overrideOptions.text=\'");


#line 23 "..\..\RazorHelpers\NotyBuilder.cshtml"
          WriteTo(__razor_helper_writer, message.Message);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\';\n");

WriteLiteralTo(__razor_helper_writer, "                ");

WriteLiteralTo(__razor_helper_writer, "var overrideAnimation={};\n");

WriteLiteralTo(__razor_helper_writer, "                ");

WriteLiteralTo(__razor_helper_writer, "overrideAnimation.open= \'animated ");


#line 25 "..\..\RazorHelpers\NotyBuilder.cshtml"
                      WriteTo(__razor_helper_writer, message.OpenAnimation);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\';\n");

WriteLiteralTo(__razor_helper_writer, "                ");

WriteLiteralTo(__razor_helper_writer, " overrideAnimation.close= \'animated ");


#line 26 "..\..\RazorHelpers\NotyBuilder.cshtml"
                        WriteTo(__razor_helper_writer, message.CloseAnimation);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\';\n");

WriteLiteralTo(__razor_helper_writer, "                ");

WriteLiteralTo(__razor_helper_writer, "overrideOptions.maxVisible= ");


#line 27 "..\..\RazorHelpers\NotyBuilder.cshtml"
                WriteTo(__razor_helper_writer, notyInput.MaxVisibleForQueue);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, ";\n");

WriteLiteralTo(__razor_helper_writer, "                ");

WriteLiteralTo(__razor_helper_writer, "overrideOptions.closeWith= [\'");


#line 28 "..\..\RazorHelpers\NotyBuilder.cshtml"
                 WriteTo(__razor_helper_writer, message.CloseWith);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\'];\n");

WriteLiteralTo(__razor_helper_writer, "                ");

WriteLiteralTo(__razor_helper_writer, "overrideOptions.buttons= false;\n");

WriteLiteralTo(__razor_helper_writer, "                ");

WriteLiteralTo(__razor_helper_writer, "overrideAnimation.speed= ");


#line 30 "..\..\RazorHelpers\NotyBuilder.cshtml"
             WriteTo(__razor_helper_writer, message.AnimateSpeed);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, ";\n");


#line 31 "..\..\RazorHelpers\NotyBuilder.cshtml"

             if (message.IsSwing)
                {


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "                    ");

WriteLiteralTo(__razor_helper_writer, " overrideAnimation.easing=\'swing\';\n");


#line 35 "..\..\RazorHelpers\NotyBuilder.cshtml"
                                             }

                if (notyInput.DismissQueue)
                {


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "                    ");

WriteLiteralTo(__razor_helper_writer, " overrideOptions.dismissQueue= true;\n");


#line 40 "..\..\RazorHelpers\NotyBuilder.cshtml"
                                            }
                if (message.IsForce)
                {


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "                    ");

WriteLiteralTo(__razor_helper_writer, "overrideOptions.force= true;\n");


#line 44 "..\..\RazorHelpers\NotyBuilder.cshtml"
                                           }
                if (message.IsKiller)
                {


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "                    ");

WriteLiteralTo(__razor_helper_writer, "overrideOptions. killer= true;\n");


#line 48 "..\..\RazorHelpers\NotyBuilder.cshtml"
                                                     }
                if (message.IsModal)
                {


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "                    ");

WriteLiteralTo(__razor_helper_writer, "overrideOptions.modal=true;\n");


#line 52 "..\..\RazorHelpers\NotyBuilder.cshtml"
                                            }
                if (message.IsSticky)
                {


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "                    ");

WriteLiteralTo(__razor_helper_writer, "overrideOptions.timeout= false;\n");


#line 56 "..\..\RazorHelpers\NotyBuilder.cshtml"

                }


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "                 ");

WriteLiteralTo(__razor_helper_writer, "overrideAnimation.fadeSpeed=50;\n");

WriteLiteralTo(__razor_helper_writer, "                 ");

WriteLiteralTo(__razor_helper_writer, "overrideOptions.animation=overrideAnimation;\n");

WriteLiteralTo(__razor_helper_writer, "                 ");

WriteLiteralTo(__razor_helper_writer, "noty(overrideOptions);\n");


#line 61 "..\..\RazorHelpers\NotyBuilder.cshtml"
                }


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "    });\n\n    </script>\n");


#line 65 "..\..\RazorHelpers\NotyBuilder.cshtml"


#line default
#line hidden
});

#line 65 "..\..\RazorHelpers\NotyBuilder.cshtml"
}
#line default
#line hidden

    }
}
#pragma warning restore 1591
