// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace IRIT.EdMS.WebUI.Areas.HumanResource.Controllers
{
    public partial class OrganizationStructureController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected OrganizationStructureController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ManageOrganization()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ManageOrganization);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult CreateOrganization()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CreateOrganization);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult CreateRole()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CreateRole);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult EditOrganization()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EditOrganization);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult EditRole()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EditRole);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult Delete()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.Delete);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult EmployeeStatute_Read()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EmployeeStatute_Read);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ManageEmployeeStatute()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ManageEmployeeStatute);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult CreateEmployeeStatute()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CreateEmployeeStatute);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult EditEmployeeStatute()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EditEmployeeStatute);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult DeleteEmployeeStatute()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.DeleteEmployeeStatute);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public OrganizationStructureController Actions { get { return MVC.HumanResource.OrganizationStructure; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "HumanResource";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "OrganizationStructure";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "OrganizationStructure";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string ManageOrganization = "ManageOrganization";
            public readonly string CreateOrganization = "CreateOrganization";
            public readonly string CreateRole = "CreateRole";
            public readonly string EditOrganization = "EditOrganization";
            public readonly string EditRole = "EditRole";
            public readonly string Delete = "Delete";
            public readonly string EmployeeStatute_Read = "EmployeeStatute_Read";
            public readonly string ManageEmployeeStatute = "ManageEmployeeStatute";
            public readonly string CreateEmployeeStatute = "CreateEmployeeStatute";
            public readonly string EditEmployeeStatute = "EditEmployeeStatute";
            public readonly string DeleteEmployeeStatute = "DeleteEmployeeStatute";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string ManageOrganization = "ManageOrganization";
            public const string CreateOrganization = "CreateOrganization";
            public const string CreateRole = "CreateRole";
            public const string EditOrganization = "EditOrganization";
            public const string EditRole = "EditRole";
            public const string Delete = "Delete";
            public const string EmployeeStatute_Read = "EmployeeStatute_Read";
            public const string ManageEmployeeStatute = "ManageEmployeeStatute";
            public const string CreateEmployeeStatute = "CreateEmployeeStatute";
            public const string EditEmployeeStatute = "EditEmployeeStatute";
            public const string DeleteEmployeeStatute = "DeleteEmployeeStatute";
        }


        static readonly ActionParamsClass_ManageOrganization s_params_ManageOrganization = new ActionParamsClass_ManageOrganization();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ManageOrganization ManageOrganizationParams { get { return s_params_ManageOrganization; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ManageOrganization
        {
            public readonly string hiddenNodeId = "hiddenNodeId";
        }
        static readonly ActionParamsClass_CreateOrganization s_params_CreateOrganization = new ActionParamsClass_CreateOrganization();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_CreateOrganization CreateOrganizationParams { get { return s_params_CreateOrganization; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_CreateOrganization
        {
            public readonly string viewModel = "viewModel";
        }
        static readonly ActionParamsClass_CreateRole s_params_CreateRole = new ActionParamsClass_CreateRole();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_CreateRole CreateRoleParams { get { return s_params_CreateRole; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_CreateRole
        {
            public readonly string viewModel = "viewModel";
        }
        static readonly ActionParamsClass_EditOrganization s_params_EditOrganization = new ActionParamsClass_EditOrganization();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_EditOrganization EditOrganizationParams { get { return s_params_EditOrganization; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_EditOrganization
        {
            public readonly string viewModel = "viewModel";
        }
        static readonly ActionParamsClass_EditRole s_params_EditRole = new ActionParamsClass_EditRole();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_EditRole EditRoleParams { get { return s_params_EditRole; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_EditRole
        {
            public readonly string viewModel = "viewModel";
        }
        static readonly ActionParamsClass_Delete s_params_Delete = new ActionParamsClass_Delete();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Delete DeleteParams { get { return s_params_Delete; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Delete
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_EmployeeStatute_Read s_params_EmployeeStatute_Read = new ActionParamsClass_EmployeeStatute_Read();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_EmployeeStatute_Read EmployeeStatute_ReadParams { get { return s_params_EmployeeStatute_Read; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_EmployeeStatute_Read
        {
            public readonly string request = "request";
            public readonly string specialityIn = "specialityIn";
        }
        static readonly ActionParamsClass_ManageEmployeeStatute s_params_ManageEmployeeStatute = new ActionParamsClass_ManageEmployeeStatute();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ManageEmployeeStatute ManageEmployeeStatuteParams { get { return s_params_ManageEmployeeStatute; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ManageEmployeeStatute
        {
            public readonly string hiddenOrgId = "hiddenOrgId";
        }
        static readonly ActionParamsClass_CreateEmployeeStatute s_params_CreateEmployeeStatute = new ActionParamsClass_CreateEmployeeStatute();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_CreateEmployeeStatute CreateEmployeeStatuteParams { get { return s_params_CreateEmployeeStatute; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_CreateEmployeeStatute
        {
            public readonly string viewModel = "viewModel";
        }
        static readonly ActionParamsClass_EditEmployeeStatute s_params_EditEmployeeStatute = new ActionParamsClass_EditEmployeeStatute();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_EditEmployeeStatute EditEmployeeStatuteParams { get { return s_params_EditEmployeeStatute; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_EditEmployeeStatute
        {
            public readonly string id = "id";
            public readonly string viewModel = "viewModel";
        }
        static readonly ActionParamsClass_DeleteEmployeeStatute s_params_DeleteEmployeeStatute = new ActionParamsClass_DeleteEmployeeStatute();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DeleteEmployeeStatute DeleteEmployeeStatuteParams { get { return s_params_DeleteEmployeeStatute; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DeleteEmployeeStatute
        {
            public readonly string id = "id";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string CreateEmployeeStatute = "CreateEmployeeStatute";
                public readonly string CreateOrganization = "CreateOrganization";
                public readonly string CreateRole = "CreateRole";
                public readonly string EditEmployeeStatute = "EditEmployeeStatute";
                public readonly string EditOrganization = "EditOrganization";
                public readonly string EditRole = "EditRole";
                public readonly string Index = "Index";
            }
            public readonly string CreateEmployeeStatute = "~/Areas/HumanResource/Views/OrganizationStructure/CreateEmployeeStatute.cshtml";
            public readonly string CreateOrganization = "~/Areas/HumanResource/Views/OrganizationStructure/CreateOrganization.cshtml";
            public readonly string CreateRole = "~/Areas/HumanResource/Views/OrganizationStructure/CreateRole.cshtml";
            public readonly string EditEmployeeStatute = "~/Areas/HumanResource/Views/OrganizationStructure/EditEmployeeStatute.cshtml";
            public readonly string EditOrganization = "~/Areas/HumanResource/Views/OrganizationStructure/EditOrganization.cshtml";
            public readonly string EditRole = "~/Areas/HumanResource/Views/OrganizationStructure/EditRole.cshtml";
            public readonly string Index = "~/Areas/HumanResource/Views/OrganizationStructure/Index.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_OrganizationStructureController : IRIT.EdMS.WebUI.Areas.HumanResource.Controllers.OrganizationStructureController
    {
        public T4MVC_OrganizationStructureController() : base(Dummy.Instance) { }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void ManageOrganizationOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string hiddenNodeId);

        [NonAction]
        public override System.Web.Mvc.ActionResult ManageOrganization(string hiddenNodeId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ManageOrganization);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "hiddenNodeId", hiddenNodeId);
            ManageOrganizationOverride(callInfo, hiddenNodeId);
            return callInfo;
        }

        [NonAction]
        partial void CreateOrganizationOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, IRIT.EdMS.HumanResource.Model.ViewModel.OrganizationStructure.OrganizationStructureViewModel viewModel);

        [NonAction]
        public override System.Web.Mvc.ActionResult CreateOrganization(IRIT.EdMS.HumanResource.Model.ViewModel.OrganizationStructure.OrganizationStructureViewModel viewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CreateOrganization);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            CreateOrganizationOverride(callInfo, viewModel);
            return callInfo;
        }

        [NonAction]
        partial void CreateRoleOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, IRIT.EdMS.HumanResource.Model.ViewModel.OrganizationStructure.RoleStructureViewModel viewModel);

        [NonAction]
        public override System.Web.Mvc.ActionResult CreateRole(IRIT.EdMS.HumanResource.Model.ViewModel.OrganizationStructure.RoleStructureViewModel viewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CreateRole);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            CreateRoleOverride(callInfo, viewModel);
            return callInfo;
        }

        [NonAction]
        partial void EditOrganizationOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, IRIT.EdMS.HumanResource.Model.ViewModel.OrganizationStructure.OrganizationStructureViewModel viewModel);

        [NonAction]
        public override System.Web.Mvc.ActionResult EditOrganization(IRIT.EdMS.HumanResource.Model.ViewModel.OrganizationStructure.OrganizationStructureViewModel viewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EditOrganization);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            EditOrganizationOverride(callInfo, viewModel);
            return callInfo;
        }

        [NonAction]
        partial void EditRoleOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, IRIT.EdMS.HumanResource.Model.ViewModel.OrganizationStructure.RoleStructureViewModel viewModel);

        [NonAction]
        public override System.Web.Mvc.ActionResult EditRole(IRIT.EdMS.HumanResource.Model.ViewModel.OrganizationStructure.RoleStructureViewModel viewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EditRole);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            EditRoleOverride(callInfo, viewModel);
            return callInfo;
        }

        [NonAction]
        partial void DeleteOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, string id);

        [NonAction]
        public override System.Web.Mvc.JsonResult Delete(string id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.Delete);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            DeleteOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void EmployeeStatute_ReadOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Kendo.Mvc.UI.DataSourceRequest request, string specialityIn);

        [NonAction]
        public override System.Web.Mvc.ActionResult EmployeeStatute_Read(Kendo.Mvc.UI.DataSourceRequest request, string specialityIn)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EmployeeStatute_Read);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "request", request);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "specialityIn", specialityIn);
            EmployeeStatute_ReadOverride(callInfo, request, specialityIn);
            return callInfo;
        }

        [NonAction]
        partial void ManageEmployeeStatuteOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string hiddenOrgId);

        [NonAction]
        public override System.Web.Mvc.ActionResult ManageEmployeeStatute(string hiddenOrgId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ManageEmployeeStatute);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "hiddenOrgId", hiddenOrgId);
            ManageEmployeeStatuteOverride(callInfo, hiddenOrgId);
            return callInfo;
        }

        [NonAction]
        partial void CreateEmployeeStatuteOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, IRIT.EdMS.HumanResource.Model.ViewModel.EmployeeStatute.EmployeeStatuteViewModel viewModel);

        [NonAction]
        public override System.Web.Mvc.ActionResult CreateEmployeeStatute(IRIT.EdMS.HumanResource.Model.ViewModel.EmployeeStatute.EmployeeStatuteViewModel viewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CreateEmployeeStatute);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            CreateEmployeeStatuteOverride(callInfo, viewModel);
            return callInfo;
        }

        [NonAction]
        partial void EditEmployeeStatuteOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, long id);

        [NonAction]
        public override System.Web.Mvc.ActionResult EditEmployeeStatute(long id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EditEmployeeStatute);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            EditEmployeeStatuteOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void EditEmployeeStatuteOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, IRIT.EdMS.HumanResource.Model.ViewModel.EmployeeStatute.EmployeeStatuteViewModel viewModel);

        [NonAction]
        public override System.Web.Mvc.ActionResult EditEmployeeStatute(IRIT.EdMS.HumanResource.Model.ViewModel.EmployeeStatute.EmployeeStatuteViewModel viewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EditEmployeeStatute);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            EditEmployeeStatuteOverride(callInfo, viewModel);
            return callInfo;
        }

        [NonAction]
        partial void DeleteEmployeeStatuteOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, string id);

        [NonAction]
        public override System.Web.Mvc.JsonResult DeleteEmployeeStatute(string id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.DeleteEmployeeStatute);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            DeleteEmployeeStatuteOverride(callInfo, id);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
