//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRIT.Framework.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GeneralResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GeneralResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IRIT.Framework.Resources.GeneralResource", typeof(GeneralResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استعفا.
        /// </summary>
        public static string Abdication {
            get {
                return ResourceManager.GetString("Abdication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درباره ما.
        /// </summary>
        public static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دسترسی.
        /// </summary>
        public static string Access {
            get {
                return ResourceManager.GetString("Access", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملیات ثبت با موفقیت انجام شد.
        /// </summary>
        public static string Add_successful {
            get {
                return ResourceManager.GetString("Add_successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن کارمند.
        /// </summary>
        public static string AddEmployee {
            get {
                return ResourceManager.GetString("AddEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتصاب کارمند به نقش.
        /// </summary>
        public static string AddEmployeeStatute {
            get {
                return ResourceManager.GetString("AddEmployeeStatute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن میدان آموزشی.
        /// </summary>
        public static string AddInfraStructureRing {
            get {
                return ResourceManager.GetString("AddInfraStructureRing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آفزودن واحد سازمانی.
        /// </summary>
        public static string AddOrganizationStructure {
            get {
                return ResourceManager.GetString("AddOrganizationStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن شخص.
        /// </summary>
        public static string AddPerson {
            get {
                return ResourceManager.GetString("AddPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن نقش سازمانی.
        /// </summary>
        public static string AddRole {
            get {
                return ResourceManager.GetString("AddRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن مدرسه.
        /// </summary>
        public static string AddSchool {
            get {
                return ResourceManager.GetString("AddSchool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن گروه مدارس.
        /// </summary>
        public static string AddSchoolsGroup {
            get {
                return ResourceManager.GetString("AddSchoolsGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن کاربر.
        /// </summary>
        public static string AddUser {
            get {
                return ResourceManager.GetString("AddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن گروه کاربر.
        /// </summary>
        public static string AddUsersGroup {
            get {
                return ResourceManager.GetString("AddUsersGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن نوع کار.
        /// </summary>
        public static string AddWorkType {
            get {
                return ResourceManager.GetString("AddWorkType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتساب.
        /// </summary>
        public static string Assignment {
            get {
                return ResourceManager.GetString("Assignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بازگشت.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ تولد.
        /// </summary>
        public static string BirthDate {
            get {
                return ResourceManager.GetString("BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هيات امنايي.
        /// </summary>
        public static string BoardOfTrustees {
            get {
                return ResourceManager.GetString("BoardOfTrustees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پسرانه.
        /// </summary>
        public static string Boys {
            get {
                return ResourceManager.GetString("Boys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برادر.
        /// </summary>
        public static string Brother {
            get {
                return ResourceManager.GetString("Brother", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انصراف.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغییر تصویر.
        /// </summary>
        public static string ChangeImage {
            get {
                return ResourceManager.GetString("ChangeImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرزند.
        /// </summary>
        public static string Child {
            get {
                return ResourceManager.GetString("Child", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شهر.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شهر محل تولد.
        /// </summary>
        public static string CityOfBirth {
            get {
                return ResourceManager.GetString("CityOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پاک کردن.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رنگ.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توضیحات.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شرکت.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مختلط.
        /// </summary>
        public static string Complex {
            get {
                return ResourceManager.GetString("Complex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات تماس.
        /// </summary>
        public static string Contact_Information {
            get {
                return ResourceManager.GetString("Contact_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تماس با ما.
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در بر داشته باشد.
        /// </summary>
        public static string Contains {
            get {
                return ResourceManager.GetString("Contains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قراردادي.
        /// </summary>
        public static string Contract {
            get {
                return ResourceManager.GetString("Contract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کشور.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کشور محل تولد.
        /// </summary>
        public static string CountryOfBirth {
            get {
                return ResourceManager.GetString("CountryOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پيماني.
        /// </summary>
        public static string Covenant {
            get {
                return ResourceManager.GetString("Covenant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشتري.
        /// </summary>
        public static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غيرمجاز.
        /// </summary>
        public static string Deny {
            get {
                return ResourceManager.GetString("Deny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سازمان.
        /// </summary>
        public static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عزل .
        /// </summary>
        public static string Deposal {
            get {
                return ResourceManager.GetString("Deposal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مطلقه.
        /// </summary>
        public static string Divorced {
            get {
                return ResourceManager.GetString("Divorced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در بر نداشته باشد.
        /// </summary>
        public static string DoesNotContain {
            get {
                return ResourceManager.GetString("DoesNotContain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جهت گروه بندی ستون ها عنوان ستون را در این قسمت درگ کنید.
        /// </summary>
        public static string DragColumnToGroup {
            get {
                return ResourceManager.GetString("DragColumnToGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویراش.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملیات ویرایش با موفقیت انجام شد.
        /// </summary>
        public static string Edit_successful {
            get {
                return ResourceManager.GetString("Edit_successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش کارمند.
        /// </summary>
        public static string EditEmployee {
            get {
                return ResourceManager.GetString("EditEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش حکم کارمند.
        /// </summary>
        public static string EditEmployeeStatute {
            get {
                return ResourceManager.GetString("EditEmployeeStatute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش میدان آموزشی.
        /// </summary>
        public static string EditInfraStructureRing {
            get {
                return ResourceManager.GetString("EditInfraStructureRing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش  واحد سازمانی.
        /// </summary>
        public static string EditOrganizationStructure {
            get {
                return ResourceManager.GetString("EditOrganizationStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش شخص.
        /// </summary>
        public static string EditPerson {
            get {
                return ResourceManager.GetString("EditPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش نقش سازمانی.
        /// </summary>
        public static string EditRole {
            get {
                return ResourceManager.GetString("EditRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش مدرسه.
        /// </summary>
        public static string EditSchool {
            get {
                return ResourceManager.GetString("EditSchool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش گروه مدارس.
        /// </summary>
        public static string EditSchoolsGroup {
            get {
                return ResourceManager.GetString("EditSchoolsGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش کاربر.
        /// </summary>
        public static string EditUser {
            get {
                return ResourceManager.GetString("EditUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش گروه کاربر.
        /// </summary>
        public static string EditUsersGroup {
            get {
                return ResourceManager.GetString("EditUsersGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش نوع کار.
        /// </summary>
        public static string EditWorkType {
            get {
                return ResourceManager.GetString("EditWorkType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایمیل.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایمیل را به شکل صحیح وارد کنید.
        /// </summary>
        public static string EmailCorrectly {
            get {
                return ResourceManager.GetString("EmailCorrectly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این ایمیل قبلا در سیستم ثبت شده است.
        /// </summary>
        public static string EmialUsed {
            get {
                return ResourceManager.GetString("EmialUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کارمند.
        /// </summary>
        public static string Employee {
            get {
                return ResourceManager.GetString("Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کارمندان.
        /// </summary>
        public static string Employees {
            get {
                return ResourceManager.GetString("Employees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فهرست کارمندان.
        /// </summary>
        public static string EmployeesList {
            get {
                return ResourceManager.GetString("EmployeesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خاتمه یابد.
        /// </summary>
        public static string EndsWith {
            get {
                return ResourceManager.GetString("EndsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا نام میدان آموزشی را وارد کنید.
        /// </summary>
        public static string EnterInfraStructureRing {
            get {
                return ResourceManager.GetString("EnterInfraStructureRing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا نوع میدان آموزشی را وارد کنید.
        /// </summary>
        public static string EnterInfraStructureRingKindID {
            get {
                return ResourceManager.GetString("EnterInfraStructureRingKindID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا نام گروه مدارس را وارد کنید.
        /// </summary>
        public static string EnterSchoolsGroupName {
            get {
                return ResourceManager.GetString("EnterSchoolsGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا نام مدرسه را وارد کنید.
        /// </summary>
        public static string EnterSchoolsName {
            get {
                return ResourceManager.GetString("EnterSchoolsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موجوديت.
        /// </summary>
        public static string Entity {
            get {
                return ResourceManager.GetString("Entity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مساوی (=).
        /// </summary>
        public static string EqualsTo {
            get {
                return ResourceManager.GetString("EqualsTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در عملیات درخواستی شما خطایی رخ داده.
        /// </summary>
        public static string ErrorInRequest {
            get {
                return ResourceManager.GetString("ErrorInRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خروج.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام پدر.
        /// </summary>
        public static string Father {
            get {
                return ResourceManager.GetString("Father", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره فکس.
        /// </summary>
        public static string FaxNo {
            get {
                return ResourceManager.GetString("FaxNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زن.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پايان کار.
        /// </summary>
        public static string FinishWork {
            get {
                return ResourceManager.GetString("FinishWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برو به صفحه اول.
        /// </summary>
        public static string First {
            get {
                return ResourceManager.GetString("First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ظرفیت برای این سمت تکمیل می باشد.
        /// </summary>
        public static string FullCapacity {
            get {
                return ResourceManager.GetString("FullCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جنسیت.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دخترانه.
        /// </summary>
        public static string Girly {
            get {
                return ResourceManager.GetString("Girly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دولتي.
        /// </summary>
        public static string Government {
            get {
                return ResourceManager.GetString("Government", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقطع تحصیلی.
        /// </summary>
        public static string GradeKind {
            get {
                return ResourceManager.GetString("GradeKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجاز.
        /// </summary>
        public static string Grant {
            get {
                return ResourceManager.GetString("Grant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}-{1} از مجموع {2} آیتم .
        /// </summary>
        public static string GridPagingMessage {
            get {
                return ResourceManager.GetString("GridPagingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صفحه اصلی.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس سایت.
        /// </summary>
        public static string HomePageURL {
            get {
                return ResourceManager.GetString("HomePageURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره شناسنامه.
        /// </summary>
        public static string IDNumber {
            get {
                return ResourceManager.GetString("IDNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سریال شناسنامه.
        /// </summary>
        public static string IDSerial {
            get {
                return ResourceManager.GetString("IDSerial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تصویر.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اندازه عکس باید کمتر از 32 کیلوبایت باشد.
        /// </summary>
        public static string ImageSizeMessage {
            get {
                return ResourceManager.GetString("ImageSizeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to باشد jpg,PNG  پسوند عکس باید  .
        /// </summary>
        public static string ImageTypeMessage {
            get {
                return ResourceManager.GetString("ImageTypeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صندوق پیام.
        /// </summary>
        public static string Inbox {
            get {
                return ResourceManager.GetString("Inbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری یا کلمه عبور صحیح نمی باشد.
        /// </summary>
        public static string IncorrectUserPass {
            get {
                return ResourceManager.GetString("IncorrectUserPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to میدان آموزشی.
        /// </summary>
        public static string InfraStructureRing {
            get {
                return ResourceManager.GetString("InfraStructureRing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد میدان.
        /// </summary>
        public static string InfraStructureRingCode {
            get {
                return ResourceManager.GetString("InfraStructureRingCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام میدان.
        /// </summary>
        public static string InfraStructureRingID {
            get {
                return ResourceManager.GetString("InfraStructureRingID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع میدان.
        /// </summary>
        public static string InfraStructureRingKindID {
            get {
                return ResourceManager.GetString("InfraStructureRingKindID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان میدان.
        /// </summary>
        public static string InfraStructureRingKindTitle {
            get {
                return ResourceManager.GetString("InfraStructureRingKindTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فهرست میدان آموزشی.
        /// </summary>
        public static string InfraStructureRingList {
            get {
                return ResourceManager.GetString("InfraStructureRingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام میدان.
        /// </summary>
        public static string InfraStructureRingName {
            get {
                return ResourceManager.GetString("InfraStructureRingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جديد.
        /// </summary>
        public static string Insert {
            get {
                return ResourceManager.GetString("Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد ملی وارد شده نا معتبر می باشد.
        /// </summary>
        public static string InvalidNationalCode {
            get {
                return ResourceManager.GetString("InvalidNationalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نا مساوی (&lt;&gt;).
        /// </summary>
        public static string IsNotEqualTo {
            get {
                return ResourceManager.GetString("IsNotEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ تاسیس.
        /// </summary>
        public static string IssueDate {
            get {
                return ResourceManager.GetString("IssueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد آیتم ها در هر صفحه.
        /// </summary>
        public static string ItemsPerPage {
            get {
                return ResourceManager.GetString("ItemsPerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فقط عدد وارد کنید.
        /// </summary>
        public static string JustNumber {
            get {
                return ResourceManager.GetString("JustNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برو به آخرین صفحه.
        /// </summary>
        public static string Last {
            get {
                return ResourceManager.GetString("Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام خانوادگی.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورود به سیستم.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرد.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت نقش ها.
        /// </summary>
        public static string ManagementRoles {
            get {
                return ResourceManager.GetString("ManagementRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متاهل.
        /// </summary>
        public static string Married {
            get {
                return ResourceManager.GetString("Married", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انجام شده.
        /// </summary>
        public static string MilitaryServiceDoned {
            get {
                return ResourceManager.GetString("MilitaryServiceDoned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معاف از خدمت.
        /// </summary>
        public static string MilitaryServiceExemption {
            get {
                return ResourceManager.GetString("MilitaryServiceExemption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انجام نشده.
        /// </summary>
        public static string MilitaryServiceUnDone {
            get {
                return ResourceManager.GetString("MilitaryServiceUnDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره موبایل.
        /// </summary>
        public static string MobileNo {
            get {
                return ResourceManager.GetString("MobileNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ماژول.
        /// </summary>
        public static string Module {
            get {
                return ResourceManager.GetString("Module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مادر.
        /// </summary>
        public static string Mother {
            get {
                return ResourceManager.GetString("Mother", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد ملی.
        /// </summary>
        public static string NationalCode {
            get {
                return ResourceManager.GetString("NationalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملیت.
        /// </summary>
        public static string Nationality {
            get {
                return ResourceManager.GetString("Nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جدید.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برو به صفحه بعد.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام مستعار.
        /// </summary>
        public static string NickName {
            get {
                return ResourceManager.GetString("NickName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خیر.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رکوردی برای نمایش وجود ندارد.
        /// </summary>
        public static string NoItemToDisplay {
            get {
                return ResourceManager.GetString("NoItemToDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رسمي.
        /// </summary>
        public static string Official {
            get {
                return ResourceManager.GetString("Official", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تایید.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to چارت سازماني.
        /// </summary>
        public static string OrganizationStructure {
            get {
                return ResourceManager.GetString("OrganizationStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ساير.
        /// </summary>
        public static string Others {
            get {
                return ResourceManager.GetString("Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to والدین.
        /// </summary>
        public static string Parents {
            get {
                return ResourceManager.GetString("Parents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت اشخاص.
        /// </summary>
        public static string PeopleManagement {
            get {
                return ResourceManager.GetString("PeopleManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دائمي.
        /// </summary>
        public static string Permanent {
            get {
                return ResourceManager.GetString("Permanent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شخص.
        /// </summary>
        public static string Person {
            get {
                return ResourceManager.GetString("Person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات فردی.
        /// </summary>
        public static string personal_Information {
            get {
                return ResourceManager.GetString("personal_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فهرست اشخاص.
        /// </summary>
        public static string PersonsList {
            get {
                return ResourceManager.GetString("PersonsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره ثابت.
        /// </summary>
        public static string PhoneNo {
            get {
                return ResourceManager.GetString("PhoneNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در این لحظه امکان ورود به  سابت وجود ندارد . مراتب را با مسئولان سایت در میان بگذارید.
        /// </summary>
        public static string PossibilityEntering {
            get {
                return ResourceManager.GetString("PossibilityEntering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کدپستی.
        /// </summary>
        public static string PostAddress {
            get {
                return ResourceManager.GetString("PostAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برو به صفحه قبل.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خصوصي.
        /// </summary>
        public static string Private {
            get {
                return ResourceManager.GetString("Private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب کاربری.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استان.
        /// </summary>
        public static string Province {
            get {
                return ResourceManager.GetString("Province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استان محل تولد.
        /// </summary>
        public static string ProvinceOfBirth {
            get {
                return ResourceManager.GetString("ProvinceOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to به روز رسانی.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت نام.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پر کردن این فیلد اجباری می باشد.
        /// </summary>
        public static string RequiredMessage {
            get {
                return ResourceManager.GetString("RequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نقش سازماني.
        /// </summary>
        public static string RoleStructure {
            get {
                return ResourceManager.GetString("RoleStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت و بازگشت.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت و جدید.
        /// </summary>
        public static string SaveNew {
            get {
                return ResourceManager.GetString("SaveNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدارس.
        /// </summary>
        public static string School {
            get {
                return ResourceManager.GetString("School", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فهرست مدارس.
        /// </summary>
        public static string SchoolList {
            get {
                return ResourceManager.GetString("SchoolList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سامانه مدیریت جامع مدرسه.
        /// </summary>
        public static string SchoolManagementSystem {
            get {
                return ResourceManager.GetString("SchoolManagementSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام مدرسه.
        /// </summary>
        public static string SchoolName {
            get {
                return ResourceManager.GetString("SchoolName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گروه مدارس.
        /// </summary>
        public static string SchoolsGroup {
            get {
                return ResourceManager.GetString("SchoolsGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد گروه.
        /// </summary>
        public static string SchoolsGroupCode {
            get {
                return ResourceManager.GetString("SchoolsGroupCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گروه مدرسه.
        /// </summary>
        public static string SchoolsGroupID {
            get {
                return ResourceManager.GetString("SchoolsGroupID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فهرست گروه مدراس.
        /// </summary>
        public static string SchoolsGroupList {
            get {
                return ResourceManager.GetString("SchoolsGroupList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام گروه.
        /// </summary>
        public static string SchoolsGroupName {
            get {
                return ResourceManager.GetString("SchoolsGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تصویر امنیتی.
        /// </summary>
        public static string SecurityImage {
            get {
                return ResourceManager.GetString("SecurityImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتخاب عکس.
        /// </summary>
        public static string SelectPhoto {
            get {
                return ResourceManager.GetString("SelectPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نيمه دولتي.
        /// </summary>
        public static string SemiGovernment {
            get {
                return ResourceManager.GetString("SemiGovernment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنظیمات.
        /// </summary>
        public static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجرد.
        /// </summary>
        public static string Single {
            get {
                return ResourceManager.GetString("Single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خواهر.
        /// </summary>
        public static string Sister {
            get {
                return ResourceManager.GetString("Sister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشخصات.
        /// </summary>
        public static string Specifications {
            get {
                return ResourceManager.GetString("Specifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to همسر.
        /// </summary>
        public static string Spouse {
            get {
                return ResourceManager.GetString("Spouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شروع شود.
        /// </summary>
        public static string StartsWith {
            get {
                return ResourceManager.GetString("StartsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد کاراکتر های این فیلد باید 10 کاراکتر باشد.
        /// </summary>
        public static string StringLength10 {
            get {
                return ResourceManager.GetString("StringLength10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد کاراکتر های این فیلد نباید کمتر از 1 و بیتشر از 10 باشد.
        /// </summary>
        public static string StringLength1To10 {
            get {
                return ResourceManager.GetString("StringLength1To10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حداکثر طول ایمیل 256 حرف است.
        /// </summary>
        public static string StringLength256 {
            get {
                return ResourceManager.GetString("StringLength256", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد کاراکتر های این فیلد نباید کمتر از 3 و بیتشر از 256 باشد.
        /// </summary>
        public static string StringLength3To256 {
            get {
                return ResourceManager.GetString("StringLength3To256", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد کاراکتر های این فیلد نباید کمتر از 8 و بیتشر از 256 باشد.
        /// </summary>
        public static string StringLength8To256 {
            get {
                return ResourceManager.GetString("StringLength8To256", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دانش آموز.
        /// </summary>
        public static string Student {
            get {
                return ResourceManager.GetString("Student", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لیست دانش آموزان.
        /// </summary>
        public static string StudentsList {
            get {
                return ResourceManager.GetString("StudentsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زيرسيستم.
        /// </summary>
        public static string SubSystem {
            get {
                return ResourceManager.GetString("SubSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تامين کننده.
        /// </summary>
        public static string Supplier {
            get {
                return ResourceManager.GetString("Supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیا از حذف گزینه مورد نظر اطمینان دارید؟.
        /// </summary>
        public static string SureDelete {
            get {
                return ResourceManager.GetString("SureDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدت دار.
        /// </summary>
        public static string Temporary {
            get {
                return ResourceManager.GetString("Temporary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نا مشخص.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ويرايش.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گروه های کاربری.
        /// </summary>
        public static string UserGroups {
            get {
                return ResourceManager.GetString("UserGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فهرست کاربران.
        /// </summary>
        public static string UserList {
            get {
                return ResourceManager.GetString("UserList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربران.
        /// </summary>
        public static string UserManagement {
            get {
                return ResourceManager.GetString("UserManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنظیمات کاربری.
        /// </summary>
        public static string UserSettings {
            get {
                return ResourceManager.GetString("UserSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کروه کاربران.
        /// </summary>
        public static string UsersGroup {
            get {
                return ResourceManager.GetString("UsersGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فهرست گروه کاربران.
        /// </summary>
        public static string UsersGroupList {
            get {
                return ResourceManager.GetString("UsersGroupList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشاهده.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع کار.
        /// </summary>
        public static string WorkType {
            get {
                return ResourceManager.GetString("WorkType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فهرست نوع کار.
        /// </summary>
        public static string WorkTypeList {
            get {
                return ResourceManager.GetString("WorkTypeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بله.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
