"""add student profile fields

Revision ID: 7731fb2a535f
Revises: 8744f40bd84f
Create Date: 2026-08-06 07:18:49.609770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7731fb2a535f'
down_revision: Union[str, Sequence[str], None] = '8744f40bd84f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('father_last_name', sa.String(length=200), nullable=True))
    op.add_column('users', sa.Column('mother_last_name', sa.String(length=200), nullable=True))
    op.add_column('users', sa.Column('major', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('academic_year', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'academic_year')
    op.drop_column('users', 'major')
    op.drop_column('users', 'mother_last_name')
    op.drop_column('users', 'father_last_name')
    # ### end Alembic commands ###
