#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using IRIT.EdMS.WebUI;
    using IRIT.Framework.Resources;
    using Kendo.Mvc.UI;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_Layout.cshtml")]
    public partial class _Views_Shared__Layout_cshtml : IRIT.Framework.Utility.View.BaseViewPage<dynamic>
    {
        public _Views_Shared__Layout_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\Shared\_Layout.cshtml"
  
    Layout = null;

            
            #line default
            #line hidden
WriteLiteral("\r\n<!DOCTYPE html>\r\n<html>\r\n<head>\r\n    <meta");

WriteLiteral(" charset=\"utf-8\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width, initial-scale=1.0\"");

WriteLiteral(">\r\n    <title>");

            
            #line 9 "..\..\Views\Shared\_Layout.cshtml"
      Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral(" - سامانه جامع مدیریت مدرسه</title>\r\n");

WriteLiteral("    ");

            
            #line 10 "..\..\Views\Shared\_Layout.cshtml"
Write(Styles.Render("~/Content/css-rtl"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 11 "..\..\Views\Shared\_Layout.cshtml"
Write(Scripts.Render("~/bundles/modernizr"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 12 "..\..\Views\Shared\_Layout.cshtml"
Write(RenderSection("styles", required: false));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 369), Tuple.Create("\"", 399)
, Tuple.Create(Tuple.Create("", 376), Tuple.Create<System.Object, System.Int32>(Href("~/Content/MenuStyle.css")
, 376), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 431), Tuple.Create("\"", 461)
, Tuple.Create(Tuple.Create("", 438), Tuple.Create<System.Object, System.Int32>(Href("~/Content/bootstrap.css")
, 438), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 493), Tuple.Create("\"", 527)
, Tuple.Create(Tuple.Create("", 500), Tuple.Create<System.Object, System.Int32>(Href("~/Content/bootstrap-rtl.css")
, 500), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 559), Tuple.Create("\"", 584)
, Tuple.Create(Tuple.Create("", 566), Tuple.Create<System.Object, System.Int32>(Href("~/Content/Site.css")
, 566), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 616), Tuple.Create("\"", 645)
, Tuple.Create(Tuple.Create("", 623), Tuple.Create<System.Object, System.Int32>(Href("~/Content/Site-rtl.css")
, 623), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <!--This bundle was moved by the Telerik VS Extensions for compatibility" +
" reasons-->\r\n");

WriteLiteral("    ");

            
            #line 19 "..\..\Views\Shared\_Layout.cshtml"
Write(Scripts.Render("~/bundles/jquery"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 807), Tuple.Create("\"", 877)
            
            #line 20 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 814), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Content/kendo/2015.3.930/kendo.common.min.css")
            
            #line default
            #line hidden
, 814), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 925), Tuple.Create("\"", 999)
            
            #line 21 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 932), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Content/kendo/2015.3.930/kendo.mobile.all.min.css")
            
            #line default
            #line hidden
, 932), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 1047), Tuple.Create("\"", 1118)
            
            #line 22 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 1054), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Content/kendo/2015.3.930/kendo.dataviz.min.css")
            
            #line default
            #line hidden
, 1054), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 1166), Tuple.Create("\"", 1237)
            
            #line 23 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 1173), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Content/kendo/2015.3.930/kendo.default.min.css")
            
            #line default
            #line hidden
, 1173), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 1285), Tuple.Create("\"", 1364)
            
            #line 24 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 1292), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Content/kendo/2015.3.930/kendo.dataviz.default.min.css")
            
            #line default
            #line hidden
, 1292), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 1412), Tuple.Create("\"", 1479)
            
            #line 25 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 1419), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Content/kendo/2015.3.930/kendo.rtl.min.css")
            
            #line default
            #line hidden
, 1419), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1529), Tuple.Create("\"", 1591)
            
            #line 26 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 1535), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Scripts/kendo/2015.3.930/jquery.min.js")
            
            #line default
            #line hidden
, 1535), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1615), Tuple.Create("\"", 1676)
            
            #line 27 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 1621), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Scripts/kendo/2015.3.930/jszip.min.js")
            
            #line default
            #line hidden
, 1621), false)
);

WriteLiteral("></script>\r\n    ");

WriteLiteral("\r\n    ");

WriteLiteral("\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1892), Tuple.Create("\"", 1949)
            
            #line 30 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 1898), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Scripts/kendo.modernizr.custom.js")
            
            #line default
            #line hidden
, 1898), false)
);

WriteLiteral("></script>\r\n</head>\r\n<body>\r\n");

WriteLiteral("    ");

            
            #line 33 "..\..\Views\Shared\_Layout.cshtml"
Write(Html.Partial("_Menu"));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n    <div");

WriteLiteral(" class=\"container body-content\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 36 "..\..\Views\Shared\_Layout.cshtml"
   Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("       \r\n    </div>\r\n    <hr />\r\n    <footer>\r\n        <p>  سامانه مدیریت جامع مد" +
"ارس</p>\r\n    </footer>\r\n    \r\n");

WriteLiteral("    ");

            
            #line 43 "..\..\Views\Shared\_Layout.cshtml"
Write(Scripts.Render("~/bundles/jquery"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 44 "..\..\Views\Shared\_Layout.cshtml"
Write(Scripts.Render("~/bundles/bootstrap"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 45 "..\..\Views\Shared\_Layout.cshtml"
Write(Scripts.Render("~/bundles/kendo"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2319), Tuple.Create("\"", 2365)
, Tuple.Create(Tuple.Create("", 2325), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/kendo/DatePicker/JalaliDate.js")
, 2325), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2389), Tuple.Create("\"", 2434)
, Tuple.Create(Tuple.Create("", 2395), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/kendo/DatePicker/kendo.web.js")
, 2395), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2458), Tuple.Create("\"", 2499)
, Tuple.Create(Tuple.Create("", 2464), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/kendo/DatePicker/fa-IR.js")
, 2464), false)
);

WriteLiteral("></script>\r\n");

            
            #line 49 "..\..\Views\Shared\_Layout.cshtml"
    
            
            #line default
            #line hidden
            
            #line 49 "..\..\Views\Shared\_Layout.cshtml"
      Html.RenderPartial(MVC.Shared.Views._Noty);
            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 50 "..\..\Views\Shared\_Layout.cshtml"
Write(RenderSection("scripts", required: false));

            
            #line default
            #line hidden
WriteLiteral("\r\n</body>\r\n</html>\r\n");

        }
    }
}
#pragma warning restore 1591
