#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using IRIT.EdMS.WebUI;
    using IRIT.Framework.Resources;
    using Kendo.Mvc.UI;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_Menu.cshtml")]
    public partial class _Views_Shared__Menu_cshtml : IRIT.Framework.Utility.View.BaseViewPage<dynamic>
    {
        public _Views_Shared__Menu_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<nav");

WriteLiteral(" class=\"navbar navbar-default navbar-static\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"navbar-header\"");

WriteLiteral(">\r\n        <button");

WriteLiteral(" class=\"navbar-toggle\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" data-toggle=\"collapse\"");

WriteLiteral(" data-target=\".js-navbar-collapse\"");

WriteLiteral(">\r\n            <span");

WriteLiteral(" class=\"sr-only\"");

WriteLiteral(">Toggle navigation</span>\r\n            <span");

WriteLiteral(" class=\"icon-bar\"");

WriteLiteral("></span>\r\n            <span");

WriteLiteral(" class=\"icon-bar\"");

WriteLiteral("></span>\r\n            <span");

WriteLiteral(" class=\"icon-bar\"");

WriteLiteral("></span>\r\n        </button>\r\n        ");

WriteLiteral("\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"collapse navbar-collapse js-navbar-collapse\"");

WriteLiteral(">\r\n       \r\n");

WriteLiteral("        ");

            
            #line 13 "..\..\Views\Shared\_Menu.cshtml"
   Write(Html.Partial(MVC.Shared.Views.MenuItem._LoginOption));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

WriteLiteral("        ");

            
            #line 15 "..\..\Views\Shared\_Menu.cshtml"
   Write(Html.Partial(MVC.Shared.Views.MenuItem._BaseInfo));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

WriteLiteral("        ");

            
            #line 17 "..\..\Views\Shared\_Menu.cshtml"
   Write(Html.Partial(MVC.Shared.Views.MenuItem._ManagementSystem));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n    </div><!-- /.nav-collapse -->\r\n</nav>\r\n");

        }
    }
}
#pragma warning restore 1591
