#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using IRIT.EdMS.WebUI;
    using IRIT.Framework.Resources;
    using Kendo.Mvc.UI;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Security/Views/Shared/_Layout.cshtml")]
    public partial class _Areas_Security_Views_Shared__Layout_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Areas_Security_Views_Shared__Layout_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<!DOCTYPE html>\r\n<html>\r\n<head>\r\n    <meta");

WriteLiteral(" charset=\"utf-8\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width, initial-scale=1.0\"");

WriteLiteral(">\r\n    <title>");

            
            #line 6 "..\..\Areas\Security\Views\Shared\_Layout.cshtml"
      Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral(" - سامانه جامع مدیریت مدرسه</title>\r\n");

WriteLiteral("    ");

            
            #line 7 "..\..\Areas\Security\Views\Shared\_Layout.cshtml"
Write(Styles.Render("~/Content/css-rtl"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 8 "..\..\Areas\Security\Views\Shared\_Layout.cshtml"
Write(Scripts.Render("~/bundles/modernizr"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 295), Tuple.Create("\"", 325)
, Tuple.Create(Tuple.Create("", 302), Tuple.Create<System.Object, System.Int32>(Href("~/Content/MenuStyle.css")
, 302), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 357), Tuple.Create("\"", 387)
, Tuple.Create(Tuple.Create("", 364), Tuple.Create<System.Object, System.Int32>(Href("~/Content/bootstrap.css")
, 364), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 419), Tuple.Create("\"", 453)
, Tuple.Create(Tuple.Create("", 426), Tuple.Create<System.Object, System.Int32>(Href("~/Content/bootstrap-rtl.css")
, 426), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n\r\n    <!--This bundle was moved by the Telerik VS Extensions for compatibili" +
"ty reasons-->\r\n");

WriteLiteral("    ");

            
            #line 14 "..\..\Areas\Security\Views\Shared\_Layout.cshtml"
Write(Scripts.Render("~/bundles/jquery"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 617), Tuple.Create("\"", 687)
            
            #line 15 "..\..\Areas\Security\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 624), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Content/kendo/2015.3.930/kendo.common.min.css")
            
            #line default
            #line hidden
, 624), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 735), Tuple.Create("\"", 809)
            
            #line 16 "..\..\Areas\Security\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 742), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Content/kendo/2015.3.930/kendo.mobile.all.min.css")
            
            #line default
            #line hidden
, 742), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 857), Tuple.Create("\"", 928)
            
            #line 17 "..\..\Areas\Security\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 864), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Content/kendo/2015.3.930/kendo.dataviz.min.css")
            
            #line default
            #line hidden
, 864), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 976), Tuple.Create("\"", 1047)
            
            #line 18 "..\..\Areas\Security\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 983), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Content/kendo/2015.3.930/kendo.default.min.css")
            
            #line default
            #line hidden
, 983), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 1095), Tuple.Create("\"", 1174)
            
            #line 19 "..\..\Areas\Security\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 1102), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Content/kendo/2015.3.930/kendo.dataviz.default.min.css")
            
            #line default
            #line hidden
, 1102), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 1222), Tuple.Create("\"", 1289)
            
            #line 20 "..\..\Areas\Security\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 1229), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Content/kendo/2015.3.930/kendo.rtl.min.css")
            
            #line default
            #line hidden
, 1229), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1339), Tuple.Create("\"", 1401)
            
            #line 21 "..\..\Areas\Security\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 1345), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Scripts/kendo/2015.3.930/jquery.min.js")
            
            #line default
            #line hidden
, 1345), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1425), Tuple.Create("\"", 1486)
            
            #line 22 "..\..\Areas\Security\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 1431), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Scripts/kendo/2015.3.930/jszip.min.js")
            
            #line default
            #line hidden
, 1431), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1510), Tuple.Create("\"", 1575)
            
            #line 23 "..\..\Areas\Security\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 1516), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Scripts/kendo/2015.3.930/kendo.all.min.js")
            
            #line default
            #line hidden
, 1516), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1599), Tuple.Create("\"", 1670)
            
            #line 24 "..\..\Areas\Security\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 1605), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Scripts/kendo/2015.3.930/kendo.aspnetmvc.min.js")
            
            #line default
            #line hidden
, 1605), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1694), Tuple.Create("\"", 1751)
            
            #line 25 "..\..\Areas\Security\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 1700), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Scripts/kendo.modernizr.custom.js")
            
            #line default
            #line hidden
, 1700), false)
);

WriteLiteral("></script>\r\n</head>\r\n<body>\r\n    \r\n    <div");

WriteLiteral(" class=\"container body-content\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 30 "..\..\Areas\Security\Views\Shared\_Layout.cshtml"
   Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\r\n        <hr />\r\n        <footer>\r\n            <p>سامانه مدیریت جامع مدارس</p>\r\n" +
"        </footer>\r\n    </div>\r\n\r\n");

WriteLiteral("    ");

            
            #line 37 "..\..\Areas\Security\Views\Shared\_Layout.cshtml"
Write(Scripts.Render("~/bundles/jquery"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 38 "..\..\Areas\Security\Views\Shared\_Layout.cshtml"
Write(Scripts.Render("~/bundles/bootstrap"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 39 "..\..\Areas\Security\Views\Shared\_Layout.cshtml"
Write(Scripts.Render("~/bundles/kendo"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 40 "..\..\Areas\Security\Views\Shared\_Layout.cshtml"
Write(RenderSection("scripts", required: false));

            
            #line default
            #line hidden
WriteLiteral("\r\n</body>\r\n</html>");

        }
    }
}
#pragma warning restore 1591
