#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using IRIT.EdMS.WebUI;
    using IRIT.Framework.Resources;
    using Kendo.Mvc.UI;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Common/Views/Party/Index.cshtml")]
    public partial class _Areas_Common_Views_Party_Index_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Areas_Common_Views_Party_Index_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 2 "..\..\Areas\Common\Views\Party\Index.cshtml"
  
    ViewBag.Title = GeneralResource.PeopleManagement;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 6 "..\..\Areas\Common\Views\Party\Index.cshtml"
Write(Styles.Render("~/Content/bootstrap-dialog"));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-md-5\"");

WriteLiteral(" style=\"padding-bottom: 10px;\"");

WriteLiteral(">\r\n                <a");

WriteAttribute("href", Tuple.Create(" href=\"", 273), Tuple.Create("\"", 351)
            
            #line 12 "..\..\Areas\Common\Views\Party\Index.cshtml"
, Tuple.Create(Tuple.Create("", 280), Tuple.Create<System.Object, System.Int32>(Url.Action(MVC.Common.Party.ActionNames.Create, MVC.Common.Party.Name)
            
            #line default
            #line hidden
, 280), false)
);

WriteLiteral(" class=\"btn btn-success\"");

WriteLiteral(">\r\n                    <i");

WriteLiteral(" class=\"fa fa-lg fa-plus\"");

WriteLiteral("></i>  ");

            
            #line 13 "..\..\Areas\Common\Views\Party\Index.cshtml"
                                                 Write(GeneralResource.New);

            
            #line default
            #line hidden
WriteLiteral("\r\n                </a>\r\n            </div>\r\n        </div>\r\n\r\n        <div");

WriteLiteral(" class=\"panel panel-primary\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"panel-heading\"");

WriteLiteral(">\r\n                <i");

WriteLiteral(" class=\"fa fa-lg fa-users\"");

WriteLiteral("></i> ");

            
            #line 20 "..\..\Areas\Common\Views\Party\Index.cshtml"
                                             Write(GeneralResource.PersonsList);

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"k-rtl\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 23 "..\..\Areas\Common\Views\Party\Index.cshtml"
            Write(Html.Kendo().Grid<IRIT.EdMS.Common.Model.ViewModel.Party.PartyViewModel>().Name("grid_Party")
                   .Columns(columns =>
                   {
                       columns.Bound(c => c.FirstName).Width(150);
                       columns.Bound(c => c.LastName).Width(160);
                       columns.Bound(c => c.FatherName).Width(160);
                       columns.Bound(c => c.NationalCode).Width(150);
                       columns.Template(x => { }).ClientTemplate(
                          "<a class='btn btn-warning' href='" + Url.Action(MVC.Common.Party.ActionNames.Edit, MVC.Common.Party.Name) + "?id=#= ID #'" + ">"+GeneralResource.Edit+"</a>" +
                          "<a class='btn-danger btn' target='#= ID #'>"+GeneralResource.Delete+"</a>");
                   })
                   .HtmlAttributes(new { style = "height: 480px;" })
                   .Scrollable()
                   .Sortable()
                   .Filterable(flt =>
                   {
                       flt.Mode(GridFilterMode.Row);
                       flt.Operators(fltOpt =>
                       {
                           fltOpt.ForString(fms => { fms.IsEqualTo(GeneralResource.EqualsTo); fms.IsNotEqualTo(GeneralResource.IsNotEqualTo); fms.StartsWith(GeneralResource.StartsWith); fms.EndsWith(GeneralResource.EndsWith); fms.Contains(GeneralResource.Contains); fms.DoesNotContain(GeneralResource.DoesNotContain); });
                           //fltOpt.ForDate(fms => { fms.IsEqualTo(GeneralResource.Equals); fms.IsNotEqualTo(GeneralResource.IsNotEqualTo); fms.StartsWith(GeneralResource.StartsWith); fms.EndsWith(GeneralResource.EndsWith); fms.Contains(GeneralResource.Contains); fms.DoesNotContain(GeneralResource.DoesNotContain); });
                       });
                   })
                   .Groupable(grp => { grp.Messages(gmsg => { gmsg.Empty(GeneralResource.DragColumnToGroup); }); })
                   .Pageable(pageable => pageable.Refresh(true).PageSizes(true).ButtonCount(5).Messages(msg => { msg.Display(GeneralResource.GridPagingMessage); msg.ItemsPerPage(GeneralResource.ItemsPerPage); msg.Refresh(GeneralResource.Refresh); msg.Last(GeneralResource.Last); msg.Next(GeneralResource.Next); msg.Previous(GeneralResource.Previous); msg.First(GeneralResource.First); }))
                   .DataSource(dataBinding => dataBinding.Ajax().Model(model => model.Id(id => id.Id))
                   .Read(read => read.Action(MVC.Common.Party.ActionNames.Party_Read, MVC.Common.Party.Name)))
                );

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n    </div>\r\n</div>\r\n\r\n");

DefineSection("Scripts", () => {

WriteLiteral(@"
    <script>
        $(document).on('click', '.btn-danger', function () {
            var rowToDelete = $(this).closest(""tr"");
            var grid = $(""#grid_userGroup"").data(""kendoGrid"");

            var pkNo = $(this).attr(""target"");
            var rowNo = '#row-' + pkNo;
            BootstrapDialog.show({
                title: '',
                message: '");

            
            #line 67 "..\..\Areas\Common\Views\Party\Index.cshtml"
                     Write(GeneralResource.SureDelete);

            
            #line default
            #line hidden
WriteLiteral("\',\r\n                buttons: [{\r\n                    label: \'");

            
            #line 69 "..\..\Areas\Common\Views\Party\Index.cshtml"
                       Write(GeneralResource.Yes);

            
            #line default
            #line hidden
WriteLiteral("\',\r\n                    action: function (dialog) {\r\n                        $.aj" +
"ax({\r\n                            type: \"POST\",\r\n                            url" +
": \"");

            
            #line 73 "..\..\Areas\Common\Views\Party\Index.cshtml"
                             Write(Url.Action(MVC.Common.Party.ActionNames.Delete, MVC.Common.Party.Name));

            
            #line default
            #line hidden
WriteLiteral(@""",
                            data: { id: pkNo },
                            cache: false,
                            dataType: ""json"",
                            success: function () {
                                dialog.close();
                                grid.removeRow(rowToDelete);
                            },
                            error: function (jqXHR, exception) {
                                alert('Uncaught Error.\n' + jqXHR.responseText);
                            }
                        });
                    }
                }, {
                    label: '");

            
            #line 87 "..\..\Areas\Common\Views\Party\Index.cshtml"
                       Write(GeneralResource.No);

            
            #line default
            #line hidden
WriteLiteral("\',\r\n                    action: function (dialog) {\r\n                        dial" +
"og.close();\r\n                    }\r\n                }]\r\n            });\r\n       " +
" });\r\n    </script>\r\n");

});

        }
    }
}
#pragma warning restore 1591
