#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using IRIT.EdMS.WebUI;
    using IRIT.Framework.Resources;
    using Kendo.Mvc.UI;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Common/Views/Shared/_Layout.cshtml")]
    public partial class _Areas_Common_Views_Shared__Layout_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Areas_Common_Views_Shared__Layout_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<!DOCTYPE html>\r\n<html>\r\n<head>\r\n    <meta");

WriteLiteral(" charset=\"utf-8\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width, initial-scale=1.0\"");

WriteLiteral(">\r\n    <title>");

            
            #line 6 "..\..\Areas\Common\Views\Shared\_Layout.cshtml"
      Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral(" - My ASP.NET Application</title>\r\n");

WriteLiteral("    ");

            
            #line 7 "..\..\Areas\Common\Views\Shared\_Layout.cshtml"
Write(Styles.Render("~/Content/css"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 8 "..\..\Areas\Common\Views\Shared\_Layout.cshtml"
Write(Scripts.Render("~/bundles/modernizr"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 289), Tuple.Create("\"", 319)
, Tuple.Create(Tuple.Create("", 296), Tuple.Create<System.Object, System.Int32>(Href("~/Content/MenuStyle.css")
, 296), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 351), Tuple.Create("\"", 381)
, Tuple.Create(Tuple.Create("", 358), Tuple.Create<System.Object, System.Int32>(Href("~/Content/bootstrap.css")
, 358), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 413), Tuple.Create("\"", 447)
, Tuple.Create(Tuple.Create("", 420), Tuple.Create<System.Object, System.Int32>(Href("~/Content/bootstrap-rtl.css")
, 420), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n\r\n    <!--This bundle was moved by the Telerik VS Extensions for compatibili" +
"ty reasons-->\r\n");

WriteLiteral("    ");

            
            #line 14 "..\..\Areas\Common\Views\Shared\_Layout.cshtml"
Write(Scripts.Render("~/bundles/jquery"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 611), Tuple.Create("\"", 681)
            
            #line 15 "..\..\Areas\Common\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 618), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Content/kendo/2015.3.930/kendo.common.min.css")
            
            #line default
            #line hidden
, 618), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 729), Tuple.Create("\"", 803)
            
            #line 16 "..\..\Areas\Common\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 736), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Content/kendo/2015.3.930/kendo.mobile.all.min.css")
            
            #line default
            #line hidden
, 736), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 851), Tuple.Create("\"", 922)
            
            #line 17 "..\..\Areas\Common\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 858), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Content/kendo/2015.3.930/kendo.dataviz.min.css")
            
            #line default
            #line hidden
, 858), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 970), Tuple.Create("\"", 1041)
            
            #line 18 "..\..\Areas\Common\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 977), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Content/kendo/2015.3.930/kendo.default.min.css")
            
            #line default
            #line hidden
, 977), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 1089), Tuple.Create("\"", 1168)
            
            #line 19 "..\..\Areas\Common\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 1096), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Content/kendo/2015.3.930/kendo.dataviz.default.min.css")
            
            #line default
            #line hidden
, 1096), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 1216), Tuple.Create("\"", 1283)
            
            #line 20 "..\..\Areas\Common\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 1223), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Content/kendo/2015.3.930/kendo.rtl.min.css")
            
            #line default
            #line hidden
, 1223), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1333), Tuple.Create("\"", 1395)
            
            #line 21 "..\..\Areas\Common\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 1339), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Scripts/kendo/2015.3.930/jquery.min.js")
            
            #line default
            #line hidden
, 1339), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1419), Tuple.Create("\"", 1480)
            
            #line 22 "..\..\Areas\Common\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 1425), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Scripts/kendo/2015.3.930/jszip.min.js")
            
            #line default
            #line hidden
, 1425), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1504), Tuple.Create("\"", 1569)
            
            #line 23 "..\..\Areas\Common\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 1510), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Scripts/kendo/2015.3.930/kendo.all.min.js")
            
            #line default
            #line hidden
, 1510), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1593), Tuple.Create("\"", 1664)
            
            #line 24 "..\..\Areas\Common\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 1599), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Scripts/kendo/2015.3.930/kendo.aspnetmvc.min.js")
            
            #line default
            #line hidden
, 1599), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1688), Tuple.Create("\"", 1745)
            
            #line 25 "..\..\Areas\Common\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 1694), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Scripts/kendo.modernizr.custom.js")
            
            #line default
            #line hidden
, 1694), false)
);

WriteLiteral("></script>\r\n</head>\r\n<body>\r\n    <div");

WriteLiteral(" class=\"container body-content\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 29 "..\..\Areas\Common\Views\Shared\_Layout.cshtml"
   Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\r\n        <hr />\r\n        <footer>\r\n            <p>&copy; ");

            
            #line 32 "..\..\Areas\Common\Views\Shared\_Layout.cshtml"
                 Write(DateTime.Now.Year);

            
            #line default
            #line hidden
WriteLiteral(" - My ASP.NET Application</p>\r\n        </footer>\r\n    </div>\r\n\r\n");

WriteLiteral("    ");

            
            #line 36 "..\..\Areas\Common\Views\Shared\_Layout.cshtml"
Write(Scripts.Render("~/bundles/jquery"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 37 "..\..\Areas\Common\Views\Shared\_Layout.cshtml"
Write(Scripts.Render("~/bundles/bootstrap"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 38 "..\..\Areas\Common\Views\Shared\_Layout.cshtml"
Write(Scripts.Render("~/bundles/kendo"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 39 "..\..\Areas\Common\Views\Shared\_Layout.cshtml"
Write(RenderSection("scripts", required: false));

            
            #line default
            #line hidden
WriteLiteral("\r\n</body>\r\n</html>");

        }
    }
}
#pragma warning restore 1591
