#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using IRIT.EdMS.WebUI;
    using IRIT.Framework.Resources;
    using Kendo.Mvc.UI;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/MenuItem/_BaseInfo.cshtml")]
    public partial class _Views_Shared_MenuItem__BaseInfo_cshtml : IRIT.Framework.Utility.View.BaseViewPage<dynamic>
    {
        public _Views_Shared_MenuItem__BaseInfo_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n<ul");

WriteLiteral(" class=\"nav navbar-nav\"");

WriteLiteral(">\r\n    <li");

WriteLiteral(" class=\"dropdown dropdown-large\"");

WriteLiteral(">\r\n        <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"dropdown-toggle\"");

WriteLiteral(" data-toggle=\"dropdown\"");

WriteLiteral("> اطلاعات پایه <b");

WriteLiteral(" class=\"caret\"");

WriteLiteral("></b></a>\r\n\r\n        <ul");

WriteLiteral(" class=\"dropdown-menu dropdown-menu-large row\"");

WriteLiteral(">\r\n            <li");

WriteLiteral(" class=\"col-sm-3\"");

WriteLiteral(">\r\n                <ul>\r\n                    <li");

WriteLiteral(" class=\"dropdown-header\"");

WriteLiteral(">مدیریت کاربران</li>\r\n                    <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 395), Tuple.Create("\"", 510)
            
            #line 10 "..\..\Views\Shared\MenuItem\_BaseInfo.cshtml"
, Tuple.Create(Tuple.Create("", 402), Tuple.Create<System.Object, System.Int32>(Url.Action(MVC.Common.Party.ActionNames.Index, MVC.Common.Party.Name, new { area = MVC.Common.Name }, null)
            
            #line default
            #line hidden
, 402), false)
);

WriteLiteral(">مدیریت اشخاص</a></li>\r\n                    <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 561), Tuple.Create("\"", 680)
            
            #line 11 "..\..\Views\Shared\MenuItem\_BaseInfo.cshtml"
, Tuple.Create(Tuple.Create("", 568), Tuple.Create<System.Object, System.Int32>(Url.Action(MVC.Security.User.ActionNames.Index, MVC.Security.User.Name, new { area = MVC.Security.Name }, null)
            
            #line default
            #line hidden
, 568), false)
);

WriteLiteral(">کاربران</a></li>\r\n                    <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 726), Tuple.Create("\"", 857)
            
            #line 12 "..\..\Views\Shared\MenuItem\_BaseInfo.cshtml"
, Tuple.Create(Tuple.Create("", 733), Tuple.Create<System.Object, System.Int32>(Url.Action(MVC.Security.UsersGroup.ActionNames.Index, MVC.Security.UsersGroup.Name, new { area = MVC.Security.Name }, null)
            
            #line default
            #line hidden
, 733), false)
);

WriteLiteral(">گروه کاربران</a></li>\r\n                    <li");

WriteLiteral(" class=\"divider\"");

WriteLiteral("></li>\r\n                    ");

WriteLiteral("\r\n                </ul>\r\n            </li>\r\n            <li");

WriteLiteral(" class=\"col-sm-3\"");

WriteLiteral(">\r\n                <ul>\r\n                    <li");

WriteLiteral(" class=\"dropdown-header\"");

WriteLiteral(">مدیریت سازمان</li>\r\n                    <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1472), Tuple.Create("\"", 1640)
            
            #line 25 "..\..\Views\Shared\MenuItem\_BaseInfo.cshtml"
, Tuple.Create(Tuple.Create("", 1479), Tuple.Create<System.Object, System.Int32>(Url.Action(MVC.HumanResource.OrganizationStructure.ActionNames.Index, MVC.HumanResource.OrganizationStructure.Name, new { area = MVC.HumanResource.Name }, null)
            
            #line default
            #line hidden
, 1479), false)
);

WriteLiteral(">چارت سازمانی</a></li>\r\n                    <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1691), Tuple.Create("\"", 1831)
            
            #line 26 "..\..\Views\Shared\MenuItem\_BaseInfo.cshtml"
, Tuple.Create(Tuple.Create("", 1698), Tuple.Create<System.Object, System.Int32>(Url.Action(MVC.HumanResource.Employee.ActionNames.Index, MVC.HumanResource.Employee.Name, new {area = MVC.HumanResource.Name}, null)
            
            #line default
            #line hidden
, 1698), false)
);

WriteLiteral(">مدیریت کارمندان</a></li>\r\n                    <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1885), Tuple.Create("\"", 2011)
            
            #line 27 "..\..\Views\Shared\MenuItem\_BaseInfo.cshtml"
, Tuple.Create(Tuple.Create("", 1892), Tuple.Create<System.Object, System.Int32>(Url.Action(MVC.Calendar.Calendar.ActionNames.Index, MVC.Calendar.Calendar.Name, new { area = MVC.Calendar.Name}, null)
            
            #line default
            #line hidden
, 1892), false)
);

WriteLiteral(">تقویم</a></li>\r\n                    <li");

WriteLiteral(" class=\"divider\"");

WriteLiteral("></li>\r\n                    <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 2102), Tuple.Create("\"", 2243)
            
            #line 29 "..\..\Views\Shared\MenuItem\_BaseInfo.cshtml"
, Tuple.Create(Tuple.Create("", 2109), Tuple.Create<System.Object, System.Int32>(Url.Action(MVC.Common.InfraStructureRing.ActionNames.Index, MVC.Common.InfraStructureRing.Name, new { area = MVC.Common.Name }, null)
            
            #line default
            #line hidden
, 2109), false)
);

WriteLiteral(">میدان آموزشی</a></li>                    \r\n                    <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 2314), Tuple.Create("\"", 2441)
            
            #line 30 "..\..\Views\Shared\MenuItem\_BaseInfo.cshtml"
, Tuple.Create(Tuple.Create("", 2321), Tuple.Create<System.Object, System.Int32>(Url.Action(MVC.Common.SchoolsGroup.ActionNames.Index, MVC.Common.SchoolsGroup.Name, new {area = MVC.Common.Name}, null)
            
            #line default
            #line hidden
, 2321), false)
);

WriteLiteral(">گروه مدراس</a></li>\r\n                    <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 2490), Tuple.Create("\"", 2605)
            
            #line 31 "..\..\Views\Shared\MenuItem\_BaseInfo.cshtml"
, Tuple.Create(Tuple.Create("", 2497), Tuple.Create<System.Object, System.Int32>(Url.Action(MVC.Common.School.ActionNames.Index, MVC.Common.School.Name, new {area = MVC.Common.Name}, null)
            
            #line default
            #line hidden
, 2497), false)
);

WriteLiteral(">مدراس</a></li>\r\n                    <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 2649), Tuple.Create("\"", 2762)
            
            #line 32 "..\..\Views\Shared\MenuItem\_BaseInfo.cshtml"
, Tuple.Create(Tuple.Create("", 2656), Tuple.Create<System.Object, System.Int32>(Url.Action(MVC.Common.Test.ActionNames.Index, MVC.Common.Test.Name, new { area = MVC.Common.Name }, null)
            
            #line default
            #line hidden
, 2656), false)
);

WriteLiteral(">تستی</a></li>\r\n                </ul>\r\n            </li>\r\n            <li");

WriteLiteral(" class=\"col-sm-3\"");

WriteLiteral(">\r\n                <ul>\r\n                    <li");

WriteLiteral(" class=\"dropdown-header\"");

WriteLiteral(">Input groups</li>\r\n                    <li><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">Basic example</a></li>\r\n                    <li><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">Sizing</a></li>\r\n                    <li><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">Checkboxes and radio addons</a></li>\r\n                    <li");

WriteLiteral(" class=\"divider\"");

WriteLiteral("></li>\r\n                    <li");

WriteLiteral(" class=\"dropdown-header\"");

WriteLiteral(">Navs</li>\r\n                    <li><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">Tabs</a></li>\r\n                    <li><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">Pills</a></li>\r\n                    <li><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">Justified</a></li>\r\n                </ul>\r\n            </li>\r\n            <li");

WriteLiteral(" class=\"col-sm-3\"");

WriteLiteral(">\r\n                <ul>\r\n                    <li");

WriteLiteral(" class=\"dropdown-header\"");

WriteLiteral(">Navbar</li>\r\n                    <li><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">Default navbar</a></li>\r\n                    <li><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">Buttons</a></li>\r\n                    <li><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">Text</a></li>\r\n                    <li><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">Non-nav links</a></li>\r\n                    <li><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">Component alignment</a></li>\r\n                    <li><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">Fixed to top</a></li>\r\n                    <li><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">Fixed to bottom</a></li>\r\n                    <li><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">Static top</a></li>\r\n                    <li><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">Inverted navbar</a></li>\r\n                </ul>\r\n            </li>\r\n        </ul" +
">\r\n    </li>\r\n</ul>");

        }
    }
}
#pragma warning restore 1591
