#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using IRIT.EdMS.WebUI;
    using IRIT.Framework.Resources;
    using Kendo.Mvc.UI;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/MenuItem/_LoginOption.cshtml")]
    public partial class _Views_Shared_MenuItem__LoginOption_cshtml : IRIT.Framework.Utility.View.BaseViewPage<dynamic>
    {
        public _Views_Shared_MenuItem__LoginOption_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<ul");

WriteLiteral(" class=\"nav navbar-nav navbar-left\"");

WriteLiteral(">\r\n    <li");

WriteLiteral(" class=\"dropdown\"");

WriteLiteral(">\r\n        <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"dropdown-toggle\"");

WriteLiteral(" data-toggle=\"dropdown\"");

WriteLiteral(" style=\"margin-top: -10px; margin-bottom: -10px\"");

WriteLiteral(">\r\n            <span");

WriteLiteral(" class=\"badge\"");

WriteLiteral(" style=\"background-color: tomato\"");

WriteLiteral(">7</span> اعلانات <h4");

WriteLiteral(" class=\"glyphicon glyphicon-comment\"");

WriteLiteral("></h4>\r\n        </a>\r\n        <ul");

WriteLiteral(" class=\"dropdown-menu\"");

WriteLiteral(">\r\n            <li><a");

WriteLiteral(" href=\"#\"");

WriteLiteral("><span");

WriteLiteral(" class=\"label label-warning\"");

WriteLiteral(">7:00</span> اعلان مربوط به ثبت و ارجاع</a></li>\r\n            <li><a");

WriteLiteral(" href=\"#\"");

WriteLiteral("><span");

WriteLiteral(" class=\"label label-warning\"");

WriteLiteral(">8:00</span> اعلان مربوط به ثبت و ارجاع</a></li>\r\n            <li><a");

WriteLiteral(" href=\"#\"");

WriteLiteral("><span");

WriteLiteral(" class=\"label label-warning\"");

WriteLiteral(">19:00</span> اعلان مربوط به ثبت و ارجاع</a></li>\r\n            <li");

WriteLiteral(" class=\"divider\"");

WriteLiteral("></li>\r\n            <li><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">مشاهده همه</a></li>\r\n        </ul>\r\n    </li>\r\n    <li");

WriteLiteral(" class=\"dropdown\"");

WriteLiteral(">\r\n        <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"dropdown-toggle\"");

WriteLiteral(" data-toggle=\"dropdown\"");

WriteLiteral(" style=\"margin-top: -10px; margin-bottom: -10px\"");

WriteLiteral(">\r\n            <span");

WriteLiteral(" class=\"badge\"");

WriteLiteral(" style=\"background-color: tomato\"");

WriteLiteral(">6</span> پیام ها <h4");

WriteLiteral(" class=\"glyphicon glyphicon-envelope\"");

WriteLiteral("></h4>\r\n        </a>\r\n        <ul");

WriteLiteral(" class=\"dropdown-menu\"");

WriteLiteral(">\r\n            <li><a");

WriteLiteral(" href=\"#\"");

WriteLiteral("><span");

WriteLiteral(" class=\"label label-warning\"");

WriteLiteral(">4:00</span> پیام درون سیستمی</a></li>\r\n            <li><a");

WriteLiteral(" href=\"#\"");

WriteLiteral("><span");

WriteLiteral(" class=\"label label-warning\"");

WriteLiteral(">13:30</span> خوش آمد گویی</a></li>\r\n            <li><a");

WriteLiteral(" href=\"#\"");

WriteLiteral("><span");

WriteLiteral(" class=\"label label-warning\"");

WriteLiteral(">15:00</span> پیاد گروهی</a></li>\r\n            <li");

WriteLiteral(" class=\"divider\"");

WriteLiteral("></li>\r\n            <li><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">مشاهده همه</a></li>\r\n        </ul>\r\n    </li>\r\n    <li");

WriteLiteral(" class=\"dropdown\"");

WriteLiteral(">\r\n        <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"dropdown-toggle\"");

WriteLiteral(" data-toggle=\"dropdown\"");

WriteLiteral(">");

            
            #line 27 "..\..\Views\Shared\MenuItem\_LoginOption.cshtml"
                                                              Write(User.FullName);

            
            #line default
            #line hidden
WriteLiteral(" <img");

WriteAttribute("src", Tuple.Create(" src=\"", 1698), Tuple.Create("\"", 1839)
            
            #line 27 "..\..\Views\Shared\MenuItem\_LoginOption.cshtml"
            , Tuple.Create(Tuple.Create("", 1704), Tuple.Create<System.Object, System.Int32>(Url.Action(MVC.Security.Account.ActionNames.RenderPhoto, MVC.Security.Account.Name, new {area = MVC.Security.Name, userId = @User.Id})
            
            #line default
            #line hidden
, 1704), false)
);

WriteLiteral(" width=\"36\"");

WriteLiteral(" height=\"36\"");

WriteLiteral(" style=\"margin-top: -10px; margin-bottom: -10px\"");

WriteLiteral(" class=\"img-circle special-img\"");

WriteLiteral("></a>\r\n        <ul");

WriteLiteral(" class=\"dropdown-menu\"");

WriteLiteral(">\r\n            <li>\r\n                <a");

WriteLiteral(" href=\"#\"");

WriteLiteral("><i");

WriteLiteral(" class=\"glyphicon glyphicon-user\"");

WriteLiteral("></i> حساب کاربری من</a>\r\n            </li>\r\n            <li>\r\n                <a" +
"");

WriteAttribute("href", Tuple.Create(" href=\"", 2147), Tuple.Create("\"", 2271)
            
            #line 33 "..\..\Views\Shared\MenuItem\_LoginOption.cshtml"
, Tuple.Create(Tuple.Create("", 2154), Tuple.Create<System.Object, System.Int32>(Url.Action(MVC.Security.Account.ActionNames.LogOff, MVC.Security.Account.Name, new {area = MVC.Security.Name}, null)
            
            #line default
            #line hidden
, 2154), false)
);

WriteLiteral("><i");

WriteLiteral(" class=\"glyphicon glyphicon-dashboard\"");

WriteLiteral("></i> تغییر مدرسه</a>\r\n            </li>\r\n            <li>\r\n                <a");

WriteLiteral(" href=\"#\"");

WriteLiteral("><i");

WriteLiteral(" class=\"glyphicon glyphicon-lock\"");

WriteLiteral("></i> تغییر کلمه عبور</a>\r\n            </li>\r\n            <li>\r\n                <" +
"a");

WriteAttribute("href", Tuple.Create(" href=\"", 2518), Tuple.Create("\"", 2642)
            
            #line 39 "..\..\Views\Shared\MenuItem\_LoginOption.cshtml"
, Tuple.Create(Tuple.Create("", 2525), Tuple.Create<System.Object, System.Int32>(Url.Action(MVC.Security.Account.ActionNames.LogOff, MVC.Security.Account.Name, new {area = MVC.Security.Name}, null)
            
            #line default
            #line hidden
, 2525), false)
);

WriteLiteral("><i");

WriteLiteral(" class=\"glyphicon glyphicon-log-out\"");

WriteLiteral("></i> خروج</a>\r\n            </li>\r\n        </ul>\r\n    </li>\r\n</ul>");

        }
    }
}
#pragma warning restore 1591
