#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using IRIT.EdMS.WebUI;
    using IRIT.Framework.Resources;
    using Kendo.Mvc.UI;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/MenuItem/_ManagementSystem.cshtml")]
    public partial class _Views_Shared_MenuItem__ManagementSystem_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared_MenuItem__ManagementSystem_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<ul");

WriteLiteral(" class=\"nav navbar-nav\"");

WriteLiteral(">\r\n    <li");

WriteLiteral(" class=\"dropdown dropdown-large\"");

WriteLiteral(">\r\n        <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"dropdown-toggle\"");

WriteLiteral(" data-toggle=\"dropdown\"");

WriteLiteral("> مدیریت سیستم <b");

WriteLiteral(" class=\"caret\"");

WriteLiteral("></b></a>\r\n\r\n        <ul");

WriteLiteral(" class=\"dropdown-menu dropdown-menu-large row\"");

WriteLiteral(">\r\n            <li");

WriteLiteral(" class=\"col-sm-3\"");

WriteLiteral(">\r\n                <ul>\r\n                    <li");

WriteLiteral(" class=\"dropdown-header\"");

WriteLiteral(">Glyphicons</li>\r\n                    <li><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">Available glyphs</a></li>\r\n                    <li");

WriteLiteral(" class=\"disabled\"");

WriteLiteral("><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">How to use</a></li>\r\n                    <li><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">Examples</a></li>\r\n                    <li");

WriteLiteral(" class=\"divider\"");

WriteLiteral("></li>\r\n                    <li");

WriteLiteral(" class=\"dropdown-header\"");

WriteLiteral(">Dropdowns</li>\r\n                    <li><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">Example</a></li>\r\n                    <li><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">Aligninment options</a></li>\r\n                    <li><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">Headers</a></li>\r\n                    <li><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">Disabled menu items</a></li>\r\n                </ul>\r\n            </li>\r\n        " +
"    <li");

WriteLiteral(" class=\"col-sm-3\"");

WriteLiteral(">\r\n                <ul>\r\n                    <li");

WriteLiteral(" class=\"dropdown-header\"");

WriteLiteral(">Button groups</li>\r\n                    <li><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">Basic example</a></li>\r\n                    <li><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">Button toolbar</a></li>\r\n                    <li><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">Sizing</a></li>\r\n                    <li><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">Nesting</a></li>\r\n                    <li><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">Vertical variation</a></li>\r\n                    <li");

WriteLiteral(" class=\"divider\"");

WriteLiteral("></li>\r\n                    <li");

WriteLiteral(" class=\"dropdown-header\"");

WriteLiteral(">Button dropdowns</li>\r\n                    <li><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">Single button dropdowns</a></li>\r\n                </ul>\r\n            </li>\r\n    " +
"        <li");

WriteLiteral(" class=\"col-sm-3\"");

WriteLiteral(">\r\n                <ul>\r\n                    <li");

WriteLiteral(" class=\"dropdown-header\"");

WriteLiteral(">Input groups</li>\r\n                    <li><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">Basic example</a></li>\r\n                    <li><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">Sizing</a></li>\r\n                    <li><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">Checkboxes and radio addons</a></li>\r\n                    <li");

WriteLiteral(" class=\"divider\"");

WriteLiteral("></li>\r\n                    <li");

WriteLiteral(" class=\"dropdown-header\"");

WriteLiteral(">Navs</li>\r\n                    <li><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">Tabs</a></li>\r\n                    <li><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">Pills</a></li>\r\n                    <li><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">Justified</a></li>\r\n                </ul>\r\n            </li>\r\n            <li");

WriteLiteral(" class=\"col-sm-3\"");

WriteLiteral(">\r\n                <ul>\r\n                    <li");

WriteLiteral(" class=\"dropdown-header\"");

WriteLiteral(">Navbar</li>\r\n                    <li><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">Default navbar</a></li>\r\n                    <li><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">Buttons</a></li>\r\n                    <li><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">Text</a></li>\r\n                    <li><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">Non-nav links</a></li>\r\n                    <li><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">Component alignment</a></li>\r\n                    <li><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">Fixed to top</a></li>\r\n                    <li><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">Fixed to bottom</a></li>\r\n                    <li><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">Static top</a></li>\r\n                    <li><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">Inverted navbar</a></li>\r\n                </ul>\r\n            </li>\r\n        </ul" +
">\r\n    </li>\r\n</ul>");

        }
    }
}
#pragma warning restore 1591
