WORKSPACE_STATUS_ACTIVE = "active"
WORKSPACE_STATUS_ARCHIVED = "archived"

ACTIVITY_STATUS_DRAFT = "draft"
ACTIVITY_STATUS_PUBLISHED = "published"
ACTIVITY_STATUS_IN_PROGRESS = "in_progress"
ACTIVITY_STATUS_SUBMITTED = "submitted"
ACTIVITY_STATUS_NEEDS_REVISION = "needs_revision"
ACTIVITY_STATUS_APPROVED = "approved"
ACTIVITY_STATUS_COMPLETED = "completed"
ACTIVITY_STATUS_ARCHIVED = "archived"

# Assignment Status
ASSIGNMENT_STATUS_ASSIGNED = "assigned"
ASSIGNMENT_STATUS_ACCEPTED = "accepted"
ASSIGNMENT_STATUS_IN_PROGRESS = "in_progress"
ASSIGNMENT_STATUS_DONE = "done"
ASSIGNMENT_STATUS_REJECTED = "rejected"

ROLE_SYSTEM_ADMIN = "system_admin"
ROLE_SCHOOL_ADMIN = "school_admin"
ROLE_TEACHER = "teacher"
ROLE_STUDENT = "student"
ROLE_PARENT = "parent"
ROLE_SUPERVISOR = "supervisor"

PERMISSION_MANAGE_SYSTEM = "system.manage"
PERMISSION_MANAGE_USERS = "users.manage"
PERMISSION_MANAGE_ROLES = "roles.manage"
PERMISSION_MANAGE_PERMISSIONS = "permissions.manage"
PERMISSION_MANAGE_WORKSPACES = "workspaces.manage"
PERMISSION_MANAGE_GROUPS = "groups.manage"
PERMISSION_MANAGE_ACTIVITIES = "activities.manage"
PERMISSION_VIEW_DASHBOARD = "dashboard.view"

# Work Status
WORK_STATUS_DRAFT = "draft"
WORK_STATUS_PUBLISHED = "published"
WORK_STATUS_IN_PROGRESS = "in_progress"
WORK_STATUS_SUBMITTED = "submitted"
WORK_STATUS_NEEDS_REVISION = "needs_revision"
WORK_STATUS_APPROVED = "approved"
WORK_STATUS_COMPLETED = "completed"
WORK_STATUS_ARCHIVED = "archived"

# Work Receiver Status
WORK_RECEIVER_STATUS_ASSIGNED = "assigned"
WORK_RECEIVER_STATUS_SEEN = "seen"
WORK_RECEIVER_STATUS_IN_PROGRESS = "in_progress"
WORK_RECEIVER_STATUS_DONE = "done"
WORK_RECEIVER_STATUS_FINISHED = "finished"

# WorkGroup Status
WORKGROUP_STATUS_ACTIVE = "active"
WORKGROUP_STATUS_ARCHIVED = "archived"
